=== Steinacher62/p-soft/XML/dtd/config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT config (language, db, ftp, www, organisation, display, authentication, cms, commonsettings, modules?)>
<!ELEMENT language EMPTY>
<!ATTLIST language 
    LanguageCode (en | de | it | fr) "de"
    RegionCode CDATA "CH"
>
<!ELEMENT db EMPTY>
<!ATTLIST db 
    Server CDATA "(local)"
    LanguageCode (en | de | it | fr) "en"
    RegionCode CDATA "US"
    Name CDATA "Psoft"
    User CDATA "PsoftuserDev"
    Password CDATA "Psoft"
    DriverClass CDATA "ch.psoft.db.MSSqlDriver"
    MultiLanguage (enable | disable) "disable"
    Port CDATA "1433"
>
<!ELEMENT ftp EMPTY>
<!ATTLIST ftp     
    FtpDocumentServer CDATA "localhost"
    FtpDocumentTempDirectory CDATA #REQUIRED
    FtpDocumentSaveDirectory CDATA #REQUIRED
    FtpDocumentHistoryDirectory CDATA #REQUIRED
    DocumentSaveURL CDATA #REQUIRED
    DocumentHistoryURL CDATA #REQUIRED
    DocumentSaveDirectory CDATA #REQUIRED
    DocumentTempDirectory CDATA #REQUIRED
    DocumentHistoryDirectory CDATA #REQUIRED
    IndexingCatalogName CDATA "SEEK_Documents"
    NumberOfDocumentVersions CDATA #REQUIRED
    FtpUser CDATA #REQUIRED
    FtpPassword CDATA #REQUIRED
>
<!ELEMENT www EMPTY>
<!ATTLIST www 
    BaseURL CDATA "/Psoft"
    Domain CDATA "localhost"
    EMail CDATA #REQUIRED
>
<!ELEMENT organisation EMPTY>
<!ATTLIST organisation 
    ShortPhoneNumber CDATA "4"
    PersonPhotoDirectory CDATA ""
    ModuleVisible (0 | 1) "1"
    OrganisationImageDirectory CDATA #REQUIRED
    LogoImageDirectory CDATA ""
    showMainJobOnly (0 | 1) "0"
    showEngagement (0 | 1) "0"
    showReportPersonData (0 | 1) "0"
    enableVisio (0 | 1) "0"
    showVageField (0 | 1) "0"
    showJournalOnlyCreator (0 | 1) "0"
    shopActive  (0 | 1) "0"
>
<!ELEMENT display EMPTY> 
<!ATTLIST display 
    RowsPerListPage CDATA "15"
    MaxTreeCaptionLength CDATA "25"
    StartUpURL CDATA ""
    ShowPartnerLogos (0 | 1) "1"
    HeaderLogo CDATA ""
    HeaderLogoURL CDATA ""
    ShowDocumentSearch (0 | 1) "1"
    HighlightColor CDATA ""
    ShowLanguageSelector (0 | 1) "1"
    MaxBreadcrumbItems CDATA "5"
    ShowNews (0 | 1) "0"
    AvailableLanguages CDATA "de"
    ShowHelpFile  (0 | 1) "0"
    SelectFontSize (0 | 1) "0"
    ApplicationName CDATA ""
    ShowPasswordrecovery  (0 | 1) "1"
    ShowPasswordChange (0 | 1) "1"
    ShowNewAccount (0 | 1) "1"
    BackgroundStartpage CDATA ""
    ShowAdmin (0 | 1) "0"
>
<!ELEMENT authentication EMPTY>
<!ATTLIST authentication 
  mode (login | anonymous | windows | windowsConfirm) #REQUIRED
  anonymousAccount CDATA "anony"
  anonymousPassword CDATA ""
>
<!ELEMENT cms EMPTY>
<!ATTLIST cms 
    CMSRootURL CDATA "/Psoft/CMSRoot"
>
<!ELEMENT commonsettings (param*) >
<!ELEMENT modules (module+) >
<!ELEMENT module (param*)>
<!ATTLIST module 
  name CDATA #REQUIRED
  enabled (0 | 1) '1'
  assemblyName CDATA #IMPLIED
  className CDATA #IMPLIED
>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param 
  name CDATA #REQUIRED
>

=== Steinacher62/p-soft/RSR/XML/config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "../dtd/config.dtd" >
<config>
    <language
        LanguageCode = "fr"
        RegionCode = "CH"
    />
    <db
        Server = "(local)"
        LanguageCode = "en"
        RegionCode = "US"
        Name = "Psoft_v3"
        User = "PsoftuserDev"
        Password = "Psoft"
        DriverClass = "ch.psoft.db.MSSqlDriver"
        MultiLanguage = "enable"
    />    
    <ftp
        FtpDocumentServer = "localhost"
        FtpDocumentSaveDirectory = "ftp_Psoft/save"
        FtpDocumentTempDirectory = "ftp_Psoft/tmp"
        FtpDocumentHistoryDirectory = "ftp_Psoft/history"
        DocumentSaveDirectory = "E:\Entwicklung\pSoft_export\source_code\Dezentral_Martin\p-soft\ftp_psoft\save"
        DocumentTempDirectory = "E:\Entwicklung\pSoft_export\source_code\Dezentral_Martin\p-soft\ftp_psoft\tmp"
        DocumentHistoryDirectory = "E:\Entwicklung\pSoft_export\source_code\Dezentral_Martin\p-soft\ftp_psoft\history"
        DocumentSaveURL = "/masterpage/ftp_Psoft/save"
        DocumentHistoryURL = "/masterpage/ftp_Psoft/history"
        IndexingCatalogName = "SEEK_Documents"
		NumberOfDocumentVersions = "-1"
    />
    <www
		BaseURL = "/Psoft_v3"
		Domain = "visual2"
		EMail = '"p-soft" &lt;info@p-soft.ch&gt;'
    />
    <organisation
        ModuleVisible = "1"
        ShortPhoneNumber = "0"
        PersonPhotoDirectory = "\\PSOFTDEV1\photo"
        OrganisationImageDirectory = "C:/Inetpub/wwwroot/Psoft_v3/Organisation/images"
    />
    <cms
        CMSRootURL = "/Psoft_v3/CMSRoot"
    />
    <display
        RowsPerListPage = "15"
        MaxTreeCaptionLength = "30"
        StartUpURL = ""
        ShowPartnerLogos = "1"
        HeaderLogo = ""
        HeaderLogoURL = ""
        ShowDocumentSearch = "1"
        HighlightColor = "#f2b400"
        ShowLanguageSelector = "1"
        MaxBreadcrumbItems = "5"
    />
    <authentication
        mode = "login"
        anonymousAccount = "anonymous"
        anonymousPassword = "PsoftAnonymous"
    />
    <modules>
        <!-- Basis -->
        <module name="report" enabled="1" assemblyName="module_dispatch" className="ch.appl.psoft.Report.ReportModule">
            <param name="headerLogoImage">PsoftDogBlack.gif</param>
            <param name="enableExcel">0</param>
        </module>

        <!-- Erweiterte Basis -->
        <module name="tasklist" enabled="1" assemblyName="module_tasklist" className="ch.appl.psoft.Tasklist.TasklistModule">
            <param name="criticalDays">4</param>
        </module>

        <!-- Applikationen -->

        <!-- HR -->
        <module name="fbs" enabled="1" assemblyName="module_fbs" className="ch.appl.psoft.FBS.FBSModule">
            <param name="showNumTitleInReport">1</param>
        </module>
        <module name="fbw" enabled="1" assemblyName="module_fbw" className="ch.appl.psoft.FBW.FBWModule" />
        <module name="lohn" enabled="1" assemblyName="module_lohn" className="ch.appl.psoft.Lohn.LohnModule">
            <param name="dbName">C:/PsoftV3_D/Psoft/ch/PSOFT/Psoft/DLA/Data/RSR_LMYYYY.ogs</param>
            <param name="budgetModus">1</param><!-- siehe LohnModule.BudgetModi -->
            <param name="mitGenehmigungsverfahren">0</param><!-- 1 bedeutet ja -->
        </module>

        <!-- Kundenerweiterungen -->
        <module name="rsr" enabled="1" assemblyName="module_rsr" className="ch.appl.psoft.RSR.RsrModule" />
    </modules>
</config>

=== Steinacher62/p-soft/TPC/XML/config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "../dtd/config.dtd" >
<config>
    <language
        LanguageCode = "de"
        RegionCode = "CH"
    />
    <db
        Server = "(local)"
        LanguageCode = "en"
        RegionCode = "US"
        Name = "Psoft_v3_tpc"
        User = "PsoftuserDev"
        Password = "Psoft"
        DriverClass = "ch.psoft.db.MSSqlDriver"
        MultiLanguage = "enable"
    />
    <ftp
        FtpDocumentServer = "localhost"
        FtpDocumentSaveDirectory = "ftp_Psoft/save"
        FtpDocumentTempDirectory = "ftp_Psoft/tmp"
        FtpDocumentHistoryDirectory = "ftp_Psoft/history"
        DocumentSaveDirectory = "C:/Inetpub/wwwroot/Psoft_tpc/ftp_Psoft/save"
        DocumentTempDirectory = "C:/Inetpub/wwwroot/Psoft_tpc/ftp_Psoft/tmp"
        DocumentHistoryDirectory = "C:/Inetpub/wwwroot/Psoft_tpc/ftp_Psoft/history"
        DocumentSaveURL = "/Psoft_tpc/ftp_Psoft/save"
        DocumentHistoryURL = "/Psoft_tpc/ftp_Psoft/history"
        IndexingCatalogName = "SEEK_Documents"
        NumberOfDocumentVersions = "-1"
    />
    <www
        BaseURL = "/Psoft_tpc"
        Domain = "localhost"
        EMail = '"p-soft" &lt;info@p-soft.ch&gt;'
    />
    <organisation
        ModuleVisible = "1"
        ShortPhoneNumber = "0"
        PersonPhotoDirectory = "C:/Inetpub/wwwroot/Psoft_tpc/person/photo"
        OrganisationImageDirectory = "C:/Inetpub/wwwroot/Psoft_tpc/Organisation/images"
    />
    <cms
        CMSRootURL = "/Psoft_tpc/CMSRoot"
    />
    <display
        RowsPerListPage = "15"
        MaxTreeCaptionLength = "30"
        StartUpURL = ""
        ShowPartnerLogos = "1"
        HeaderLogo = ""
        HeaderLogoURL = ""
        ShowDocumentSearch = "1"
        HighlightColor = "#f2b400"
        ShowLanguageSelector = "1"
        MaxBreadcrumbItems = "5"
    />
    <authentication
        mode = "login"
        anonymousAccount = ""
        anonymousPassword = ""
    />
    <modules>
        <!-- Basis -->
        <module name="report" enabled="1" assemblyName="module_dispatch" className="ch.appl.psoft.Report.ReportModule">
            <param name="headerLogoImage">PsoftDogBlack.gif</param>
            <param name="enableExcel">1</param>
        </module>
        <module name="dispatch" enabled="1" assemblyName="module_dispatch" className="ch.appl.psoft.Dispatch.DispatchModule">
            <param name="eMailAddressFrom">"Andreas Delmenico" &lt;ade@PSOFT.ch&gt;</param>
            <param name="testEmailAddress">"Andreas Delmenico" &lt;ade@PSOFT.ch&gt;</param>
            <param name="smtpServer">smtp.PSOFT.ch</param>
        </module>

        <!-- Erweiterte Basis -->
        <module name="tasklist" enabled="1" assemblyName="module_tasklist" className="ch.appl.psoft.Tasklist.TasklistModule">
            <param name="criticalDays">4</param>
        </module>

        <!-- Applikationen -->
        <module name="fbw" enabled="1" assemblyName="module_fbw" className="ch.appl.psoft.FBW.FBWModule" />
        <module name="lohn" enabled="1" assemblyName="module_lohn" className="ch.appl.psoft.Lohn.LohnModule">
            <param name="dbName">\\sfdrs.local\shares\TPCOGSData\Mandanten\tpcYYYY.ogs</param>
            <param name="budgetModus">2</param><!-- siehe LohnModule.BudgetModi -->
            <param name="mitGenehmigungsverfahren">1</param><!-- 1 bedeutet ja -->
            <param name="salaireExportTemplate">salaireExportTemplate.xls</param>
            <param name="primeExportTemplate">primeExportTemplate.xls</param>
        </module>

        <!-- Kundenerweiterungen -->
        <module name="tpc" enabled="1" assemblyName="module_tpc" className="ch.appl.psoft.TPC.TPCModule"/>
    </modules>
</config>
