=== Steinacher62/p-soft/XML/dtd/language.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT map (global?, local*)>
<!ELEMENT global (prop | enum)*>
<!ELEMENT local (prop | enum)*>
<!ELEMENT enum (prop+)>
<!ELEMENT prop (#PCDATA)>
<!ATTLIST local 
    scope CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ATTLIST prop 
   mnemo CDATA #REQUIRED
   size CDATA "-1,-1"
>
<!ATTLIST enum name CDATA #REQUIRED>

=== Steinacher62/p-soft/Knowledge/XML/language_FR.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
  <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
  <local scope="ModuleNames">
    <prop mnemo="knowledge">WISSEN</prop>
  </local>
  <local scope="tableName">
    <prop mnemo="KNOWLEDGE_V">Savoir</prop>
    <prop mnemo="KNOWLEDGE">Savoir</prop>
    <prop mnemo="THEME">Thème</prop>
  </local>
  <local scope="knowledge">
    <prop mnemo="knowledge">Savoir</prop>
    <prop mnemo="miSearchKnowledge">Recherche savoir</prop>
    <prop mnemo="miNewKnowledge">Nouvel élément de savoir global</prop>
    <prop mnemo="miPrintKnowledge">Imprimer savoir</prop>
    <prop mnemo="bcSearchKnowledge">Rechercher savoir</prop>
    <prop mnemo="bcPrintKnowledge">Imprimer savoir</prop>
    <prop mnemo="bcEditTheme">Travailler thème</prop>
    <prop mnemo="bcAddTheme">Ajouter thème</prop>
    <prop mnemo="bcEditKnowledge">Travailler élément de savoir</prop>
    <prop mnemo="bcAddKnowledge">Ajouter élément de savoir global</prop>
    <prop mnemo="ctContents">Sommaire</prop>
    <prop mnemo="ctKnowledge">Elément de savoir</prop>
    <prop mnemo="ctAssignedKnowledges">Savoir relié</prop>
    <prop mnemo="ctAdministration">Administration</prop>
    <prop mnemo="clEditKnowledge">Travailler élément de savoir</prop>
    <prop mnemo="clNewKnowledge">Relier à nouvel élément de savoir</prop>
    <prop mnemo="clDeleteKnowledge">Effacer élément de savoir</prop>
    <prop mnemo="clAddTheme">Nouveau thème</prop>
    <prop mnemo="clAddDocument">Nouveau document</prop>
    <prop mnemo="clAddImage">Nouvelle image </prop>
    <prop mnemo="clInviteAuthors">Inviter auteurs</prop>
    <prop mnemo="stDocuments">Documents</prop>
    <prop mnemo="stRegistry">Enregistrement</prop>
    <prop mnemo="bcEditHistory">Travailler remarque</prop>
    <prop mnemo="bcAddHistory">Créer nouvelle version</prop>
    <prop mnemo="ttGenerateWordDocument">Générer Document Word...</prop>
    <prop mnemo="btPrintSelection">Imprimer</prop>
    <prop mnemo="cbKnowledgeOnly">Lister uniquement les éléments de savoir</prop>
    <prop mnemo="popupCannotDeleteKnowledge">Avertissement: cet élément de savoir ne peut pas être effacé</prop>
    <prop mnemo="stSuggestionRanking">Evaluation de la proposition</prop>
    <prop mnemo="ttAndOder">Relier le titre et le type de thème avec et ou alors></prop>
    <prop mnemo="columnKnowledgeTitle">Titre élément de savoir</prop>
    <prop mnemo="saveAndContinue">Enregistrer</prop>
    <prop mnemo="saveAndContinueTooltip">Enregistrer en cache</prop>
    <prop mnemo="saveAndQuit">Fermer</prop>
    <prop mnemo="saveAndQuitTooltip">Enregistrer et fermer</prop>
  </local>
  <local scope="KNOWLEDGE_V" alias="KNOWLEDGE"></local>
  <local scope="KNOWLEDGE">
    <prop mnemo="TITLE_FR" size="80,1">Titre</prop>
    <prop mnemo="DESCRIPTION_FR" size="100,25">Description</prop>
    <prop mnemo="CREATED_FR">Créé le</prop>
    <prop mnemo="CREATOR_PERSON_ID_FR">Créé par</prop>
    <prop mnemo="TRIGGER_UID">Source</prop>
    <prop mnemo="THEMETYPE_ID_FR" size="80,1">Type</prop>
    <prop mnemo="TYPE" size="80,1">Type</prop>
    <prop mnemo="ISACTIVE" size="80,1">Evaluation</prop>
    <prop mnemo="SUGGESTION_EXECUTION_ID" size="80,1">Proposition</prop>
    <prop mnemo="SUGGESTION_STATI_ID" size="80,1">Evaluation</prop>
    <enum name="types">
      <prop mnemo="0">Par défaut</prop>
      <prop mnemo="1">Proposition</prop>
    </enum>
    <enum name="isActiveSuggestion">
      <prop mnemo="0">Inactif</prop>
      <prop mnemo="1">Actif</prop>
    </enum>
  </local>
  <local scope="THEME">
    <prop mnemo="TITLE_DE" size="80,1">Titre élément de savoir</prop>
    <prop mnemo="TITLE" size="80,1">Titre du thème</prop>
    <prop mnemo="DESCRIPTION" size="100,25">Description</prop>
    <prop mnemo="CREATED">Créé le</prop>
    <prop mnemo="CREATOR_PERSON_ID">Créé par</prop>
    <prop mnemo="ORDNUMBER">Position</prop>
    <prop mnemo="THEMETYPE_ID">Type</prop>
  </local>
</map>

=== Steinacher62/p-soft/RSR/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="rsr">LOHN</prop>
    </local>
    <local scope="rsr">
        <prop mnemo="salaryChangePercentage">Lohnänderung in %</prop>
        <prop mnemo="salaryPercentageOfProposed">% vom Richtlohn</prop>
        <prop mnemo="proposedSalaryDifference">Differenz zum Richtlohn</prop>
        <prop mnemo="proposedSalaryPercentageDifference">Differenz zum Richtlohn in %</prop>
        <prop mnemo="salaireBudgetAllocation">Budget für Lohnmassnahmen</prop>
        <prop mnemo="primeBudgetAllocation">Budget für Prämien</prop>
        <prop mnemo="salaireadjustment">Lohnmassnahmen vornehmen</prop>
        <prop mnemo="primeadjustment">Prämieneingabe</prop>
        <prop mnemo="salaireApprovement">Genehmigung der Lohnmassnahmen</prop>
        <prop mnemo="primeApprovement">Genehmigung der Prämien</prop>
        <prop mnemo="salaireBudgetCheck">Budgetkontrolle für Lohnmassnahmen</prop>
        <prop mnemo="primeBudgetCheck">Budgetkontrolle für Prämien</prop>
        <prop mnemo="salaireoverview">Lohnmassnahmen Überblick</prop>
        <prop mnemo="primeoverview">Prämien Überblick</prop>
        <prop mnemo="salaireExport">Lohn exportieren</prop>
        <prop mnemo="primeExport">Pr&#228;mie exportieren</prop>
        <prop mnemo="salarySituation">Lohnsituation #1</prop>
        <prop mnemo="situation">Situation #1</prop>
        <prop mnemo="salaireLink">Lohnmassnahmen</prop>
        <prop mnemo="primeLink">Prämien</prop>
        <prop mnemo="prime">Prämie</prop>
    </local>
    <local scope="PERSON">
        <prop mnemo="AGE">Alter</prop>
    </local>
    <local scope="FUNKTION">
        <prop mnemo="TITLE_DE_REP">Stellvertredende Funktion</prop>
    </local>
    <local scope="JOB">
        <prop mnemo="REPFUNKTION_BONUS">Stellvertretende Funktionszulage</prop>
    </local>
    <local scope="EMPLOYMENT">
        <prop mnemo="EMPLOYMENTTYP">Anstellungsvertrag</prop>
        <prop mnemo="EMPLOYMENTKIND">Anstellungsverhältnis</prop>
        <prop mnemo="COSTCENTER_NUMBER">Kostenstelle</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Kostenstelle</prop>
        <prop mnemo="SUPERIOR">Hierarchisch Vorgesetzter</prop>
    </local>
    <local scope="RSR_LOHNDATEN_V" alias="LOHN">
        <prop mnemo="PNAME">Name</prop>
        <prop mnemo="FIRSTNAME">Vorname</prop>
        <prop mnemo="ENTRY">Eintrittsdatum</prop>
        <prop mnemo="AGE">Alter</prop>
        <prop mnemo="TITLE_DE">Anstellung</prop>
        <prop mnemo="ENGAGEMENT">Beschäftigungsgrad</prop>
        <prop mnemo="EMPLOYMENTTYP">Anstellungsvertrag</prop>
        <prop mnemo="EMPLOYMENTKIND">Anstellungsverhältnis</prop>
        <prop mnemo="COSTCENTER_NUMBER">Kostenstelle</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Kostenstelle</prop>
        <prop mnemo="SUPERIOR">Hierarchisch Vorgesetzter</prop>
        <prop mnemo="SALAIRE">Lohnänderung</prop>
        <prop mnemo="PRIME">Prämie</prop>
        <prop mnemo="INDEMNITE_DE_FONCTION">Funktionszulage</prop>
        <prop mnemo="FORFAIT_B">Forfaits B</prop>
        <prop mnemo="ISTLOHN">Istlohn</prop>
        <prop mnemo="LOHNVORSCHLAG">Richtlohn</prop>
    	<prop mnemo="NEUER_LOHN">Neuer Lohn</prop>
        <prop mnemo="KOMMENTARS">Kommentar Salär</prop>
        <prop mnemo="KOMMENTARP">Kommentar Prämie</prop>
        <prop mnemo="INFORMATIONP">Information Prämie</prop>
        <prop mnemo="INFORMATIONS">Kommentar Salär</prop>
        <prop mnemo="REPRICHTLOHN">Stellvertredender Richtlohn</prop>
    </local>
    <local scope="RSR_LISTE_V" alias="PERSON">
        <prop mnemo="TITLE_DE">Funktion</prop>
        <prop mnemo="BUDGETTYP_ID">Budget</prop>
        <prop mnemo="EMPLOYMENTTYP">Anstellungsvertrag</prop>
        <prop mnemo="EMPLOYMENTKIND">Anstellungsverhältnis</prop>
        <prop mnemo="COSTCENTER_NUMBER">Kostenstelle</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Kostenstelle</prop>
        <prop mnemo="SUPERIOR">Hierarch. Vorgesetzter</prop>
    	<prop mnemo="ISTLOHN">Istlohn</prop>
    	<prop mnemo="NEUER_LOHN">Neuer Lohn</prop>
    	<prop mnemo="RICHTLOHN">Richtlohn</prop>
    	<prop mnemo="LOHNVORSCHLAG">Richtlohn</prop>
    	<prop mnemo="ZUNAHME_PROZENT">% Erhöhung</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Status</prop>
        <prop mnemo="BETRAG">Lohnanpassung Jahr Fr</prop>
        <prop mnemo="BETRAG_PRO_STUNDE">Lohnanpassung Std Fr</prop>
        <prop mnemo="ISTLOHN_PROZENT">Ist % vom Richtlohn</prop>
    	<prop mnemo="NEUER_LOHN_PRO_ISTLOHN">%</prop>
    	<prop mnemo="NEUER_STUNDENLOHN">Neuer Stundenlohn</prop>
    	<prop mnemo="NEUER_LOHN_PROZENT">Neu % vom Richtlohn</prop>
        <prop mnemo="KOMMENTARS">Kommentar</prop>
        <prop mnemo="KOMMENTARP">Kommentar</prop>
        <prop mnemo="ENGAGEMENT">Beschäftigung</prop>
        <prop mnemo="VERGLEICH">Vergleichsstundenlohn</prop>
    </local>
    <local scope="SALAIRE" alias="RSR_LISTE_V">
    </local>
    <local scope="PRIME" alias="RSR_LISTE_V">
    </local>
    <local scope="OVERVIEW_SALAIRE" alias="RSR_LISTE_V">
    </local>
    <local scope="OVERVIEW_PRIME" alias="RSR_LISTE_V">
    </local>
</map>

=== Steinacher62/p-soft/Contact/XML/language_FR.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="contact">KONTAKTE</prop>
    </local>
    <local scope="home">
        <prop mnemo="myContacts">Kontaktgruppen</prop>
    </local>
    <local scope="reportLayout">
        <prop mnemo="contactGroupLetter">Wählen Sie eine Vorlage für den Serienbrief:</prop>
        <prop mnemo="contactGroupEmail">Wählen Sie eine Vorlage für das Serien-Email:</prop>
        <prop mnemo="contactsLetter">Wählen Sie eine Vorlage für das Serienbrief:</prop>
        <prop mnemo="contactsEmail">Wählen Sie eine Vorlage für das Serien-Email:</prop>
        <prop mnemo="firmLetter">Wählen Sie eine Vorlage für das Serienbrief:</prop>
        <prop mnemo="firmEmail">Wählen Sie eine Vorlage für das Serien-Email:</prop>

        <prop mnemo="SerialLetterContactGroup">Serienbrief an alle Kontakte innerhalb Kontaktgruppe</prop>
        <prop mnemo="SerialEmailContactGroup">Serien - E-Mail an alle Kontakte innerhalb Kontaktgruppe</prop>
        <prop mnemo="SerialLetterContactSelection">Serienbrief an alle selektierten Kontakte</prop>
        <prop mnemo="SerialEmailContactSelection">Serien - E-Mail an alle selektierten Kontakte</prop>
        <prop mnemo="SerialLetterContactFirm">Serienbrief an alle Kontaktpersonen der gewählten Firma</prop>
        <prop mnemo="SerialEmailContactFirm">Serien - E-Mail an alle Kontaktpersonen der gewählten Firma</prop>
    </local>
    <local scope="CONTACT_PERSON" alias="PERSON"></local>
    <local scope="PERSON">
        <prop mnemo="CONTACT_TYPE_ID">Kontakttyp</prop>
        <prop mnemo="CONTACT_ROLE_ID">Kontaktrolle</prop>
    </local>
    <local scope="CONTACT_FIRM" alias="FIRM"></local>
    <local scope="FIRM">
        <prop mnemo="CONTACT_TYPE_ID">Kontakttyp</prop>
    </local>
    <local scope="CONTACT_GROUP_CONTACT_V" alias="CONTACTV"></local>
    <local scope="CONTACTV">
        <prop mnemo="NAME" size="50">Kontaktname</prop>
        <prop mnemo="TABLENAME">Kontaktart</prop>
        <prop mnemo="COUNTRY">Land</prop>
        <prop mnemo="ZIP">PLZ</prop>
        <prop mnemo="CITY">Ort</prop>
        <prop mnemo="PHONE">Telefon</prop>
        <prop mnemo="MOBILE">Mobil</prop>
        <prop mnemo="EMAIL">Email</prop>
        <prop mnemo="FIRM_ID">Kontaktfirma</prop>
        <prop mnemo="CONTACT_TYPE_ID">Kontakttyp</prop>
        <prop mnemo="CONTACT_ROLE_ID">Kontaktrolle</prop>
    </local>
    <local scope="CONTACT_GROUP">
        <prop mnemo="TITLE">Bezeichnung</prop>
        <prop mnemo="DESCRIPTION" size="80,8">Beschreibung</prop>
    </local>
    <local scope="CONTACT_MAILINGV">
        <prop mnemo="NAME">Name</prop>
        <prop mnemo="FIRSTNAME">Vorname</prop>
        <prop mnemo="EMAIL">E-Mail</prop>
    </local>
    <local scope="JOURNAL_CONTACT_V" alias="JOURNAL"></local>
    <local scope="JOURNAL">
 		<prop mnemo="TITLE">Bezeichnung</prop>
 		<prop mnemo="DESCRIPTION" size="80,8">Beschreibung</prop>
 		<prop mnemo="CREATED">Datum</prop>
 		<prop mnemo="JOURNAL_TYPE_ID">Journaltyp</prop>
 		<prop mnemo="CREATOR_PERSON_ID">Erstellt</prop>
    </local>
    <local scope="contact">
        <prop mnemo="searchContactContact">Kontakt:</prop>
        <prop mnemo="searchContactJournal">Journal:</prop>
        <prop mnemo="contactKindPerson">Person</prop>
        <prop mnemo="contactKindFirm">Firma</prop>
        <prop mnemo="addEditContactContact">Kontaktperson:</prop>
        <prop mnemo="addEditContactFirm">Kontaktfirma:</prop>
        <prop mnemo="addEditContactAddress">Adresse:</prop>

        <prop mnemo="bcSearchContact">Kontakte suchen</prop>
        <prop mnemo="bcAddContact">Kontaktperson hinzufügen</prop>
        <prop mnemo="bcAddFirm">Kontaktfirma hinzufügen</prop>
        <prop mnemo="bcAddContactGroup">Kontaktgruppe hinzufügen</prop>
        <prop mnemo="bcEditContact">Kontaktperson bearbeiten</prop>
        <prop mnemo="bcEditFirm">Kontaktfirma bearbeiten</prop>
        <prop mnemo="bcAddJournal">Neuer Journaleintrag</prop>
        <prop mnemo="bcEditContactGroup">Kontaktgruppe bearbeiten</prop>
        <prop mnemo="bcEmptyContactGroup">Leere Kontaktgruppe</prop>
        <prop mnemo="bcNoContactGroup">Keine Kontaktgruppe definiert</prop>
        
        <prop mnemo="ptSearchContact">Kontakte suchen</prop>
        <prop mnemo="ptSearchContactList">Folgende Kontakte wurden gefunden:</prop>
        
        <prop mnemo="ctContactListSearchResult">Kontakte gemäss Selektion:</prop>
        <prop mnemo="ctContactGroupList">Kontakte in Kontaktgruppe '#1':</prop>
        <prop mnemo="ctFirmContactList">Kontaktpersonen in Firma '#1':</prop>
        <prop mnemo="ctPersonContactGroups">Vorhandene Kontaktgruppen:</prop>
        <prop mnemo="ctContactJournalList">Journaleinträge für Kontakt '#1':</prop>

        <prop mnemo="cmEditContact">Kontakt bearbeiten</prop>
        <prop mnemo="cmDeleteContact">Kontakt löschen</prop>
        <prop mnemo="cmDeleteFromGroup">Aus Kontaktgruppe entfernen</prop>
        <prop mnemo="cmDeleteFromSelection">Aus Selektion entfernen</prop>
        <prop mnemo="cmNewJournal">Neuer Journaleintrag</prop>
        <prop mnemo="cmListJournal">Journaleinträge</prop>
        <prop mnemo="cmNewContactPerson">Neue Kontaktperson</prop>
        <prop mnemo="cmListContactPersons">Kontaktpersonen</prop>
        <prop mnemo="cmListContacts">Kontakte</prop>
        <prop mnemo="cmSaveAsGroups">Als neue Kontaktgruppe</prop>
        <prop mnemo="cmEditContactGroup">Kontaktgruppe bearbeiten</prop>
        <prop mnemo="cmSerialLetter">Serienbrief/Etiketten</prop>
        <prop mnemo="cmSerialEmail">Serien - E-Mail</prop>
        <prop mnemo="cmCreateTasklist">Pendenzenliste erstellen</prop>
        <prop mnemo="cmAddToGroup">Weitere Kontakte hinzufügen</prop>
        <prop mnemo="cmAddToSelection">Weitere Kontakte hinzufügen</prop>

        <prop mnemo="cmtContactPerson">Kontaktperson</prop>
        <prop mnemo="cmtContactFirm">Kontaktfirma</prop>
        <prop mnemo="cmtContactGroup">Kontaktgruppe</prop>
        <prop mnemo="cmtAllContactGroups">Alle Kontaktgruppen</prop>
        <prop mnemo="cmtSelectionContacts">Selektierte Kontakte</prop>
        <prop mnemo="cmtGroupContacts">Kontakte in Gruppe</prop>
        <prop mnemo="cmtFirmContacts">Kontakte in Firma</prop>
        <prop mnemo="cmtDispatch">Versand</prop>
        <prop mnemo="cmtTasklists">Pendenzenlisten</prop>

        <prop mnemo="subNavTitle">Kontakte</prop>
        <prop mnemo="subNavSearchContact">Kontakte suchen</prop>
        <prop mnemo="subNavMyContactGroups">Kontaktgruppen</prop>
        <prop mnemo="subNavNewContactGroup">Neue Kontaktgruppe</prop>
        <prop mnemo="subNavNewContactPerson">Neue Kontaktperson</prop>
        <prop mnemo="subNavNewContactCompany">Neue Kontaktfirma</prop>
        
        <prop mnemo="oeAssignContactGroup">Zuordnung zu den Abteilungen</prop>
    </local>

    <!-- alte Einträge -->
    <local scope="CONTACTMAILINGV" alias="CONTACTPERSONMAILINGV"></local>
    <local scope="CONTACTPERSONMAILINGV" alias="PERSON">
        <prop mnemo="CONTACT_NAME" size="100">Kontakt</prop>
        <prop mnemo="NAME" size="100">Name</prop>
        <prop mnemo="ADR_4">Anschrift</prop>
        <prop mnemo="ADR_5">PLZ/Ort</prop>
    </local>
</map>

=== Steinacher62/p-soft/Training/XML/language_EN.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="training">AUSBILDUNG</prop>
    </local>
    <local scope="training">
        <prop mnemo="subnavTitle">Ausbildung</prop>
        <prop mnemo="subnavSearch">Massnahme suchen</prop>
        <prop mnemo="bcAdvancement">Ausbildungsmassnahmen</prop>
        <prop mnemo="bcEditAdvancement">Ausbildungsmassnahmen bearbeiten</prop>
        <prop mnemo="bcAddAdvancement">Neue Ausbildungsmassnahme</prop>
        <prop mnemo="bcSearchAdvancement">Ausbildungsmassnahmen suchen</prop>
        <prop mnemo="bcTrainingCatalog">Ausbildungskatalog</prop>
        <prop mnemo="ctTrainingGroupTree">Katalog</prop>
        <prop mnemo="ctAdvancementList">Ausbildungsmassnahmen für '#1':</prop>
        <prop mnemo="ctAdvancementDetail">Massnahme</prop>
        <prop mnemo="ctTrainingDetail">Ausbildung</prop>
        <prop mnemo="ctAdvancementSearchList">Gefundene Ausbildungsmassnahmen</prop>
        <prop mnemo="ctTrainingCatalogTrainingDetail">Ausbildung</prop>
        <prop mnemo="ctTrainingCatalogGroupDetail">Ausbildungskategorie</prop>
        <prop mnemo="cmAdvancment">Ausbildungsmassnahmen</prop>
        <prop mnemo="cmEditAdvancment">Ausbildungsmassnahme bearbeiten</prop>
        <prop mnemo="cmAddAdvancement">Neue Ausbildungsmassnahme</prop>
        <prop mnemo="cmDeleteAdvancement">Ausbildungsmassnahme löschen</prop>
        <prop mnemo="cmtTraining">Ausbildung</prop>
        <prop mnemo="flagAdvancementInheritTree">Ausbildungsmassnahme aus Ausbildungskatalog</prop>
        <prop mnemo="flagShowDoneAdvancement">erledigte Ausbildungsmassnahmen anzeigen</prop>
        <prop mnemo="lblSummaryTitle">Kosten</prop>
        <prop mnemo="lblCostCurrancy">Fr.</prop>
        <prop mnemo="lblCostIntern">Int.</prop>
        <prop mnemo="lblCostExtern">Ext.</prop>
        <prop mnemo="repPersonTraining">Ausbildung</prop>
        <prop mnemo="repAdvancement">Ausbildungsmassnahme</prop>
        <prop mnemo="repStandaloneAdvancement">Freie Gruppe</prop>
        <prop mnemo="repTrainingCatalog">Ausbildungskatalog</prop>
        <prop mnemo="repControlling">Ausbildungskontrolle</prop>
        <enum name="state">
            <prop mnemo="0">Offen</prop>
            <prop mnemo="1">Erledigt</prop>
        </enum>
    </local>
    <local scope="TRAINING" alias="TRAININGADVANCEMENTTRAININGV"></local>
    <local scope="TRAININGADVANCEMENTTRAININGV" alias="TRAINING_ADVANCEMENT">
        <prop mnemo="VALID_FROM">Gültig ab</prop>
        <prop mnemo="VALID_TO">Gülitig bis</prop>
        <prop mnemo="PARTICIPANT_NUMBER">Teilnehmerzahl</prop>
    </local>
    <local scope="TRAINING_ADVANCEMENT">
        <prop mnemo="TITLE_DE">Bezeichnung</prop>
        <prop mnemo="DESCRIPTION_DE" size="80,8">Beschreibung</prop>
        <prop mnemo="DONE_DATE">Erledigt am</prop>
        <prop mnemo="TOBEDONE_DATE">Erledigen bis</prop>
        <prop mnemo="COST_EXTERNAL">Kosten Extern</prop>
        <prop mnemo="COST_INTERNAL">Kosten Intern</prop>
        <prop mnemo="LOCATION">Kursort</prop>
        <prop mnemo="INSTRUCTOR">Kursleiter</prop>
        <prop mnemo="CREATED">Erstellt am</prop>
        <prop mnemo="TRAINING_DEMAND_ID">Ausbildungsbedarf</prop>
        <prop mnemo="RESPONSIBLE_PERSON_ID">Verantwortlich</prop>
        <prop mnemo="STATE">Status</prop>
        <prop mnemo="PERSON_ID">Mitarbeiter</prop>
        <prop mnemo="CONTROLLING_DE" size="80,8">Controlling</prop>
    </local>
</map>

=== Steinacher62/p-soft/Report/XML/language_IT.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="report">REPORT</prop>
    </local>
    <local scope="reportLayout">
        <prop mnemo="selectBreadcrumb">Listenvorlagen</prop>
        <prop mnemo="stand">Stand</prop>
        <prop mnemo="page">Seite</prop>
        <prop mnemo="pageFrom">von</prop>
        <prop mnemo="total">Total</prop>
        <prop mnemo="selectTitle">Bitte wählen Sie eine Listenvorlage:</prop>
        <prop mnemo="PhoneListAll">Mitarbeiterliste (alle erfassten Mitarbeiter)</prop>
        <prop mnemo="PhoneListAllHeader">Liste aller Mitarbeiter</prop>
        <prop mnemo="PhoneListColumnSurname">Name</prop>
        <prop mnemo="PhoneListColumnFirstname">Vorname</prop>
        <prop mnemo="PhoneListColumnNames">Nachname, Vorname</prop>
        <prop mnemo="PhoneListColumnPhone">Telefon</prop>
        <prop mnemo="PhoneListColumnMobile">Mobile</prop>
        <prop mnemo="PhoneListColumnEmail">E-Mail</prop>
        <prop mnemo="PhoneListColumnMnemo">Kürzel</prop>
        <prop mnemo="PhoneListColumnOrgentity">Abteilung</prop>
        <prop mnemo="PhoneListOE">Mitarbeiterliste (Abteilung)</prop>
        <prop mnemo="PhoneListOEHeader1">Mitarbeiterliste, lookup[title;orgentity;id=$0;false]</prop>
        <prop mnemo="PhoneListOEHeader2">Aufgelistet werden alle Mitarbeiter in der Abteilung lookup[title;orgentity;id=$0;false]</prop>
        <prop mnemo="PhoneListSearchResult">Mitarbeiterliste (aus Suchresultat)</prop>
        <prop mnemo="PhoneListSearchResultHeader">Mitarbeiterliste gemäss Selektion</prop>
        <prop mnemo="PersonObjectiveHeader">Persönliche Ziele</prop>
        <prop mnemo="SerialEmailAccessor">Serienmail an alle Berechtigte</prop>
    </local>
    <local scope="REPORTLAYOUT">
        <prop mnemo="TITLE_MNEMO">Liste</prop>
    </local>
    <local scope="ACCESSOR_PERSON_MAILINGV">
        <prop mnemo="NAME">Name</prop>
        <prop mnemo="FIRSTNAME">Vorname</prop>
        <prop mnemo="EMAIL">E-Mail</prop>
    </local>
    <local scope="Lohnsimulation">
            <prop mnemo="paramSim">Parameter Lohnsimulation</prop>
            <prop mnemo="stdSim">Standard Simulation</prop>
            <prop mnemo="valPoint">Wert/Punkt</prop>
            <prop mnemo="Unit">CHF</prop>
            <prop mnemo="totalSumCorr">Gesamtlohnsummenkorrektur</prop>
            <prop mnemo="abs">Absolut</prop>
            <prop mnemo="rel">Relativ</prop>
            <prop mnemo="fixChange">Fixe Lohnänderung</prop>
            <prop mnemo="diffNomAct">Abweichung Soll-/Istlohn</prop>
            <prop mnemo="changePercent">Änderung</prop>
            <prop mnemo="incBaseSalary">Erhöhung Basislohn</prop>
            <prop mnemo="showReport">Anzeigen</prop>
            <prop mnemo="subOEs">inkl. untergeordneten Organisationseinheiten</prop>
            <prop mnemo="jobDescription">Stellenbezeichnung</prop>
            <prop mnemo="titleEinstelllohn">Simulation Einstelllohn</prop>
            <prop mnemo="nameLabel">Nachname</prop>
            <prop mnemo="vornameLabel">Vorname</prop>
            <prop mnemo="lohnvorstellungLabel">Lohnvorstellung</prop>
            <prop mnemo="leistungsanteilLabel">Leistungsanteil</prop>
            <prop mnemo="alterLabel">Alter</prop>
            <prop mnemo="exportOptions">Exportoptionen</prop>
            <prop mnemo="correctionExport">Solllohnkorrekturen exportieren</prop>
            <prop mnemo="addressExport">Adressdaten Serienbrief exportieren</prop>
        <prop mnemo="maxIncrease">Maximale individuelle Erhöhung</prop>
        <prop mnemo="round">Lohnerhöhung runden</prop>
    </local>
    <local scope="ApplRights">
        <prop mnemo="selPerson">Bericht erstellen für</prop>
        <prop mnemo="ShowFor">Berechtigungen anzeigen für</prop>
        <prop mnemo="OR">oder</prop>
        <prop mnemo="OE">Organisation</prop>
        <prop mnemo="Person">Person</prop>
        <prop mnemo="showReport">Report anzeigen</prop>
    </local>
    <local scope="SelectNameOE">
        <prop mnemo="Title">Auswahl für Bericht "Eigeneinschätzung"</prop>
        <prop mnemo="OR">oder</prop>
        <prop mnemo="OE">Organisation</prop>
        <prop mnemo="SubOEs">auch untergeordnete OEs auflisten</prop>
        <prop mnemo="Person">Person</prop>
        <prop mnemo="showReport">Report anzeigen</prop>
        <prop mnemo="NotFound">keine Person ausgewählt oder keine Personen in gewählter OE vorhanden!</prop>
    </local>
    <local scope="LBUnterdurchschn">
        <prop mnemo="title">Unterduchschnittliche Leistungsbewertungen</prop>
    </local>
    <local scope="LBNegVeraenderung">
        <prop mnemo="title">Personen mit negativer Leistungsentwicklung</prop>
        <prop mnemo="datarange">Nur Abweichungen grösser</prop>
    </local>
    <local scope="SelectOEDateRange">
        <prop mnemo="selOE">OE wählen</prop>
        <prop mnemo="selDateRange">Zeitraum wählen</prop>
        <prop mnemo="selDateRangeBonus">Zeitraum der Leistungsbewertungen wählen</prop>
        <prop mnemo="from">von</prop>
        <prop mnemo="to">bis</prop>
        <prop mnemo="SubOEs">auch untergeordnete OEs auflisten</prop>
        <prop mnemo="showReport">Report anzeigen</prop>
        <prop mnemo="searchTitle">Personen ohne Leistungsbewertung suchen</prop>
    </local>
    <local scope="SearchPersonIncompletePerformanceRating">
        <prop mnemo="selOE">OE wählen</prop>
        <prop mnemo="selDateRange">Zeitraum wählen</prop>
        <prop mnemo="from">von</prop>
        <prop mnemo="to">bis</prop>
        <prop mnemo="SubOEs">auch untergeordnete OEs auflisten</prop>
        <prop mnemo="showReport">Report anzeigen</prop>
        <prop mnemo="searchTitle">Personen mit unvollständigen Leistungsbewertung suchen</prop>
    </local>
    <local scope="WageTable">
        <prop mnemo="OrgentityTitle">Abteilung</prop>
        <prop mnemo="PERSONNELNUMBER">P-Nr.</prop>
        <prop mnemo="PNAME">Name</prop>
        <prop mnemo="FIRSTNAME">Vorname</prop>
        <prop mnemo="JobTitle">Stellenbezeichnung</prop>
        <prop mnemo="TARIFLOEHNER">Im Tariflohn</prop>
        <prop mnemo="TARIFLOHN">Tariflohn</prop>
        <prop mnemo="AUSSERTARIFLOHN">Aussertariflicher Lohn</prop>
        <prop mnemo="AUSSCHLUSSLOHN">Ausschluss Lohn</prop>
        <prop mnemo="AUSSCHLUSS">Ausschluss von Simulation</prop>
        <prop mnemo="AUSSCHLUSSBIS">Ausschluss bis</prop>
        <prop mnemo="WAGE">Lohn</prop>
    </local>
  <local scope="SelectKnowledge">
    <prop mnemo="selectKnowledgeElement">Wissenselemt auswählen</prop>
    <prop mnemo="searchTitle">Wissenselemnet selektieren</prop>
  </local>
</map>
