=== Steinacher62/p-soft/XML/dtd/language.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT map (global?, local*)>
<!ELEMENT global (prop | enum)*>
<!ELEMENT local (prop | enum)*>
<!ELEMENT enum (prop+)>
<!ELEMENT prop (#PCDATA)>
<!ATTLIST local 
    scope CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ATTLIST prop 
   mnemo CDATA #REQUIRED
   size CDATA "-1,-1"
>
<!ATTLIST enum name CDATA #REQUIRED>

=== Steinacher62/p-soft/Lohn/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="lohn">LOHN</prop>
    </local>
    <local scope="lohn">
        <prop mnemo="division">Bereich</prop>
        <prop mnemo="budgetComp">Budgetvergleich</prop>
        <prop mnemo="clear">Freigeben</prop>
        <prop mnemo="clearAll">Alle Freigeben</prop>
        <prop mnemo="clearAllocationAll">Alle Verteilungen Freigeben</prop>
        <prop mnemo="print">Drucken</prop>
        <prop mnemo="previous">Vorheriges</prop>
        <prop mnemo="history">Vorjahre</prop>
        <prop mnemo="next">Nächstes</prop>
        <prop mnemo="terminate">Abschliessen</prop>
        <prop mnemo="terminatePrompt">Abschlussbest&#228;tigung</prop>
        <prop mnemo="admin">Stati Administrieren</prop>
        <prop mnemo="importExport">Importieren vom und Exportieren zum OGS System</prop>
        <prop mnemo="import">Importieren</prop>
        <prop mnemo="dbNameLabel">OGS Datenbank</prop>
        <prop mnemo="budgetConfirmation">Die Anpassungen wurden noch nicht bei allen Mitarbeitern Ihres Bereiches vorgenommen. Sind Sie sicher, dass Sie das Budget abschliessen wollen?</prop>
        <prop mnemo="hours">Stunden</prop>
        <prop mnemo="days">Tage</prop>
        <prop mnemo="months">Monate</prop>
        <prop mnemo="showAll">Alle anzeigen</prop>
        <prop mnemo="showAlladjustment">Alle anzeigen</prop>
        <prop mnemo="showAlloverview">Alle ab dieser OE</prop>
        <prop mnemo="exportExcel">Export Excel</prop>
        <prop mnemo="budgetGroup">Budgetverteilung</prop>
        <prop mnemo="editingGroup">Lohnanpassung</prop>
        <prop mnemo="genehmigungGroup">Genehmigung</prop>
        <prop mnemo="budgetCheckGroup">Budgetkontrolle</prop>
        <prop mnemo="overviewGroup">Übersicht</prop>
        <prop mnemo="administrationGroup">Administration</prop>
        <prop mnemo="importExportLink">Import/Export</prop>
        <prop mnemo="shortDay">T</prop>
        <prop mnemo="subOE">Direkt unterstellte OE's</prop>
        <prop mnemo="genehmigenTitle">Genehmigen</prop>
        <prop mnemo="resetTitle">Bearbeiten</prop>
        <prop mnemo="differenzVerteilbar">Differenz verteilbar</prop>
        <prop mnemo="differenzVerfuegbar">Differenz verfügbar</prop>
        <prop mnemo="loadAllOK">Vollständiger Import der Daten erfolgreich abgeschlossen</prop>
        <prop mnemo="loadAllError">Vollständiger Import der Daten fehlgeschlagen (siehe Log-file)</prop>
        <prop mnemo="approveAll">Alles genehmigen</prop>
        <prop mnemo="approve">Genehmigen</prop>
        <prop mnemo="closeApprove">Abschliessen/Genehmigen</prop>
        <prop mnemo="komponente">Komponente</prop>
        <prop mnemo="with_salaire">Mit Lohnmassnahmen</prop>
        <prop mnemo="without_salaire">Ohne Lohnmassnahmen</prop>
        <prop mnemo="with_prime">Mit Prämie</prop>
        <prop mnemo="without_prime">Ohne Prämie</prop>
        <enum name="genehmigenValue">
            <prop mnemo="0"></prop>
            <prop mnemo="1">genehmigen</prop>
            <prop mnemo="2">rückgängig</prop>
        </enum>
        <enum name="resetValue">
            <prop mnemo="0"></prop>
            <prop mnemo="1">nochmals</prop>
        </enum>
        <enum name="salaryType">
            <prop mnemo="1">Jahreslohn</prop>
            <prop mnemo="2">Monatslohn</prop>
            <prop mnemo="3">Tageslohn</prop>
            <prop mnemo="4">Stundenlohn</prop>
        </enum>
        <enum name="editingState">
            <prop mnemo="0">ausstehend</prop>
            <prop mnemo="1">abgeschlossen</prop>
            <prop mnemo="2">genehmigt</prop>
        </enum>
        <enum name="clearingState">
            <prop mnemo="0">gesperrt</prop>
            <prop mnemo="1">Verteilung freigegeben</prop>
            <prop mnemo="2">freigegeben</prop>
        </enum>
    </local>
    <local scope="KOMPONENTE">
    	<prop mnemo="BEZEICHNUNG">Bezeichnung</prop>
    	<prop mnemo="BUDGET">Gesamtbudget</prop>
    	<prop mnemo="BUDGET_IN_PROZENT">Budget in %</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
    </local>
    <local scope="BUDGET">
    	<prop mnemo="BETRAG">Budget</prop>
    	<prop mnemo="BETRAG_VERTEILBAR">Verteilbares Budget</prop>
    	<prop mnemo="KOMPONENTE_ID">Komponente</prop>
    	<prop mnemo="ORGENTITY_ID">OE</prop>
    	<prop mnemo="BUDGETTYP_ID">Budgettyp</prop>
    </local>
    <local scope="LOHNKOMPONENTE">
    	<prop mnemo="BETRAG">Anpassung pro Jahr in CHF</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Status</prop>
    	<prop mnemo="KOMPONENTE_ID">Komponente</prop>
    	<prop mnemo="LOHN_ID">Lohn</prop>
    	<prop mnemo="BUDGET_ID">Budget</prop>
    </local>
    <local scope="LOHN">
    	<prop mnemo="LOHNART">Lohnart</prop>
    	<prop mnemo="ANZAHL_LOEHNE">Anzahl L&#246;hne</prop>
    	<prop mnemo="ANZAHL_STUNDEN">Anzahl Stunden</prop>
    	<prop mnemo="ANZAHL_TAGE">Anzahl Tage</prop>
    	<prop mnemo="ISTLOHN">Istlohn pro Jahr</prop>
    	<prop mnemo="NEUER_LOHN">Neuer Lohn pro Jahr</prop>
    	<prop mnemo="RICHTLOHN">Richtlohn pro Jahr</prop>
    	<prop mnemo="LOHNVORSCHLAG">Lohnvorschlag pro Jahr</prop>
    	<prop mnemo="AUSSCHLUSS_LOHN">Ausschluss Lohn</prop>
    	<prop mnemo="AUSSCHLUSS">Ausschluss Berechnung</prop>
    	<prop mnemo="AUSSCHLUSS_BIS">Ausschluss bis</prop>
    	<prop mnemo="BERECHNUNG_ERFOLGREICH">Berechnung erfolgreich</prop>
    	<prop mnemo="GRUND">Fehler</prop>
    	<prop mnemo="HERANFUEHRUNG">Heranf&#252;hrung ber&#252;cksichtigen</prop>
        <prop mnemo="INFORMATION">Information</prop>
        <prop mnemo="KOMMENTAR">Kommentar</prop>
        <prop mnemo="KOMMENTARL">Kommentar Lohn</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
    	<prop mnemo="EMPLOYMENT_ID">Anstellung</prop>
    </local>
    <local scope="EMPLOYMENT_PERSON_OE_V" alias="PERSON">
    	<prop mnemo="OE_TITLE_DE">Zust&#228;ndige OE</prop>
    	<prop mnemo="TITLE_DE">Anstellung</prop>
    	<prop mnemo="ENGAGEMENT">Besch&#228;ftigungsgrad</prop>
    </local>
    <local scope="EMPLOYMENT">
    	<prop mnemo="ORGENTITY_ID">F&#252;r Lohn zust&#228;ndige OE</prop>
    	<prop mnemo="BUDGETTYP_ID">Budgettyp</prop>
    </local>
    <local scope="DLA_ORGENTITY_V" alias="ORGENTITY">
        <prop mnemo="FUNKTION_TITLE">Funktion</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Status</prop>
        <prop mnemo="FREIGABESTATUS">Freigabe</prop>
        <prop mnemo="ABWEICHUNG">Positive Abweichungen</prop>
        <prop mnemo="VERTEILBAR">Verteilbar</prop>
        <prop mnemo="VERFUEGBAR">Verfügbar</prop>
        <prop mnemo="VERTEILT">Verteilt</prop>
        <prop mnemo="DIFFERENZ">Differenz</prop>
    	<prop mnemo="BUDGETTYP">Budgettyp</prop>
        <prop mnemo="AUFWAND">Verwendet</prop>
        <prop mnemo="PNAME">Vorgesetzter</prop>
    </local>
    <local scope="BUDGET_V">
        <prop mnemo="TITLE_DE">Abteilung</prop>
    	<prop mnemo="BETRAG">Budget</prop>
    	<prop mnemo="BETRAG_VERTEILBAR">Verteilbares Budget</prop>
    	<prop mnemo="KOMPONENTE">Komponente</prop>
    	<prop mnemo="ORGENTITY_ID">OE</prop>
    	<prop mnemo="BUDGETTYP">Budgettyp</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Bearbeitungsstatus</prop>
        <prop mnemo="FREIGABESTATUS">Freigabestatus</prop>
        <prop mnemo="AUFWAND">Verwendet</prop>
        <prop mnemo="DIFFERENZ">Differenz</prop>
        <prop mnemo="KOMP_BEZEICHNUNG">Komponente</prop>
    </local>
    <local scope="AgeTables">
      <prop mnemo="table">Tabelle</prop>
      <prop mnemo="LiveAge">Lebensalter</prop>
      <prop mnemo="ServiceAge">Dienstalter</prop>
      <prop mnemo="AgeTable">Alterstabelle</prop>
      <prop mnemo="ServiceAgeTable">Dienstalterstabelle</prop>
      <prop mnemo="save">speichern</prop>
    </local>
</map>

=== Steinacher62/p-soft/Knowledge/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="knowledge">WISSEN</prop>
    </local>
    <local scope="tableName">
 		<prop mnemo="KNOWLEDGE_V">Wissen</prop>
 		<prop mnemo="KNOWLEDGE">Wissen</prop>
 		<prop mnemo="THEME">Thema</prop>
    </local>
    <local scope="knowledge">
        <prop mnemo="knowledge">Wissen</prop>
        <prop mnemo="miSearchKnowledge">Wissen suchen</prop>
        <prop mnemo="miNewKnowledge">Neues globales Wissenselement</prop>
        <prop mnemo="miPrintKnowledge">Wissen drucken</prop>
        <prop mnemo="bcSearchKnowledge">Wissen suchen</prop>
        <prop mnemo="bcPrintKnowledge">Wissen drucken</prop>
        <prop mnemo="bcEditTheme">Thema bearbeiten</prop>
        <prop mnemo="bcAddTheme">Thema hinzufügen</prop>
        <prop mnemo="bcEditKnowledge">Wissenselement bearbeiten</prop>
        <prop mnemo="bcAddKnowledge">Globales Wissenselement hinzufügen</prop>
        <prop mnemo="ctContents">Inhaltsverzeichnis</prop>
        <prop mnemo="ctKnowledge">Wissenselement</prop>
        <prop mnemo="ctAssignedKnowledges">Verknüpftes Wissen</prop>
        <prop mnemo="ctAdministration">Administration</prop>
        <prop mnemo="clEditKnowledge">Wissenselement bearbeiten</prop>
        <prop mnemo="clNewKnowledge">Mit neuem Wissenselement verknüpfen</prop>
        <prop mnemo="clDeleteKnowledge">Wissenselement löschen</prop>
        <prop mnemo="clAddTheme">Neues Thema</prop>
        <prop mnemo="clAddDocument">Neues Dokument</prop>
        <prop mnemo="clAddImage">Neues Bild</prop>
        <prop mnemo="clInviteAuthors">Autoren einladen</prop>
        <prop mnemo="stDocuments">Dokumente</prop>
        <prop mnemo="stRegistry">Registratur</prop>
        <prop mnemo="bcEditHistory">Bemerkung bearbeiten</prop>
        <prop mnemo="bcAddHistory">Neue Version erstellen</prop>
        <prop mnemo="ttGenerateWordDocument">Word Dokument erzeugen...</prop>
        <prop mnemo="btPrintSelection">Auswahl drucken</prop>
        <prop mnemo="cbKnowledgeOnly">Liste von Wissenelemente</prop>
        <prop mnemo="popupCannotDeleteKnowledge">Das Wissenelement kann nicht gelöscht werden, da es möglicherweise in einer Matrix eingetragen ist.</prop>
        <prop mnemo="stSuggestionRanking">Bewertung des Vorschlags</prop>
        <prop mnemo="ttAndOder">Titel mit Thementyp mit&#13;&#10;- 'und' oder,&#13;&#10;- 'oder'&#13;&#10;verkn&#252;pfen</prop>
        <prop mnemo="thColumnKnowledgeTitle">Wissenelement Titel</prop>
        <prop mnemo="saveAndContinue">Speichern</prop>
        <prop mnemo="saveAndContinueTooltip">Zwischenspeichern</prop>
        <prop mnemo="saveAndQuit">Schliessen</prop>
        <prop mnemo="saveAndQuitTooltip">Speichern und schliessen</prop>
    </local>
    <local scope="KNOWLEDGE_V" alias="KNOWLEDGE">
            <prop mnemo="TITLE_DE" size="80,1">Titel</prop>
    </local>
    <local scope="HISTORY" alias="KNOWLEDGE">
        <prop mnemo="CREATOR_PERSON_ID_DE">Durchgeführt von</prop>        
        <prop mnemo="VERSION">Version</prop>        
    </local>        
    <local scope="KNOWLEDGE">
        <prop mnemo="TITLE_DE" size="80,1">Titel</prop>
        <prop mnemo="DESCRIPTION_DE" size="100,25">Beschreibung</prop>
        <prop mnemo="CREATED_DE">Erstellt am</prop>
        <prop mnemo="CREATOR_PERSON_ID_DE">Erstellt durch</prop>
        <prop mnemo="TRIGGER_UID">Quelle</prop>
        <prop mnemo="REASON">Bemerkung</prop>
        <prop mnemo="CREATED">Geändert am</prop>
        <prop mnemo="THEMETYPE_ID_DE" size="80,1">Thementyp</prop>
        <prop mnemo="TYPE" size="80,1">Typ</prop>
        <prop mnemo="ISACTIVE" size="80,1">Art</prop>
        <prop mnemo="SUGGESTION_EXECUTION_ID" size="80,1">Vorschlag</prop>
        <prop mnemo="SUGGESTION_STATI_ID" size="80,1">Bewertung</prop>
        <enum name="types">
            <prop mnemo="0">Standard</prop>
            <prop mnemo="1">Vorschlag</prop>
        </enum>
        <enum name="isActiveSuggestion">
            <prop mnemo="0">Inaktiv</prop>
            <prop mnemo="1">Aktiv</prop>
        </enum>
    </local>
    <local scope="THEME">
        <prop mnemo="TITLE_DE" size="80,1">Wissenelement</prop>
        <prop mnemo="TITLE" size="80,1">Titel</prop>
        <prop mnemo="DESCRIPTION" size="100,25">Beschreibung</prop>
        <prop mnemo="CREATED">Erstellt am</prop>
        <prop mnemo="CREATOR_PERSON_ID">Erstellt durch</prop>
        <prop mnemo="ORDNUMBER">Position</prop>
        <prop mnemo="THEMETYPE_ID">Typ</prop>
    </local>
    <local scope="SLAVE_CHARACTERISTIC">
        <prop mnemo="TITLE" size="80,1">Titel</prop>
        <prop mnemo="DESCRIPTION" size="100,25">Beschreibung</prop>
    </local>
    <local scope="COLORATION_HISTORY">
        <prop mnemo="COLORATION_ID" size="80,1">Bewertung</prop>
        <prop mnemo="TITLE" size="80,1">Bemerkung</prop>
    </local>
</map>

=== Steinacher62/p-soft/FBS/XML/language_FR.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="fbs">DESCRIPTION DE FONCTION</prop>
    </local>
    <local scope="fbs">
        <prop mnemo="bcJobDescription">Description du emploi</prop>
        <prop mnemo="bcEditJobDescription">Remanier la description d'emploi</prop>
        <prop mnemo="bcDutyCatalog">Catalogue de tâche</prop>
        <prop mnemo="ctDutyGroupTree">Groupes de tâches</prop>
        <prop mnemo="ctDutyTree">Catalogue de tâche</prop>
        <prop mnemo="ctCompetenceList">Tâches</prop>
        <prop mnemo="ctCompetences">Compétences (dépendant du temps)</prop>
        <prop mnemo="ctDCVList">Compétences (dépendant du temps) pour la tâche '#1':</prop>
        <prop mnemo="ctDutyCatalogDutyDetail">Tâche</prop>
        <prop mnemo="cmEditJobDescription">Remanier la description d'emploi</prop>
        <prop mnemo="cmNewDutyCompetence">Nouvelle compétence (dépendant du temps)</prop>
        <prop mnemo="cmtJobDescription">Description d'emploi</prop>
        <prop mnemo="repJobDescription">Description d'emploi</prop>
        <prop mnemo="repDuty">Tâche</prop>
        <prop mnemo="repCompetences">Compétences</prop>
        <prop mnemo="repCompetencesRules">Règlement de compétence</prop>
        <prop mnemo="repJobOwner">Propriétaire de place</prop>
        <prop mnemo="repDutyCatalog">Catalogue de tâche</prop>
        <prop mnemo="repDutyGroupFree">Tâches libres</prop>
        <prop mnemo="cmAddDutyCompetence">Nouvelle compétence du catalogue</prop>
        <prop mnemo="cmAddDutyCompetenceFree">Nouvelle compétence libre</prop>
        <prop mnemo="bcAddDutyCompetence">Nouvelle compétence du catalogue</prop>
        <prop mnemo="bcAddDutyCompetenceFree">Nouvelle compétence libre</prop>
        <prop mnemo="bcEditDutyCompetence">Remanier la compétence</prop>
        <prop mnemo="ctCompetence">Tâche</prop>
        <prop mnemo="cbShowValidOnly">Indiquer seulement des compétences valables</prop>
        <prop mnemo="cmEditDutyFree">Remanier une tâche libre</prop>
        <prop mnemo="bcEditDutyFree">Remanier une tâche libre</prop>
        <prop mnemo="ctDuty">Tâche</prop>
        <prop mnemo="functionCatalog">Catalogue de fonction</prop>
        <prop mnemo="functionSearch">Chercher une fonction</prop>
        <prop mnemo="functionDescription">Description de fonction</prop>
        <prop mnemo="functionRating">Évaluation de fonction</prop>
        <prop mnemo="functionValue:">Valeur de fonction:</prop>
        <prop mnemo="salaryValue:">Salaire de base:</prop>
        <prop mnemo="responsabilityMatrixTitle">Responsabilité</prop>
        <prop mnemo="competenceMatrixTitle">Compétence</prop>
        <prop mnemo="organisationUnitSelection">Organisationseinheit selektieren</prop>
        <prop mnemo="staffmember">Mitarbeiter/-in</prop>
        <prop mnemo="directchief">Direkte/r Vorgesetzte/r</prop>
        <prop mnemo="nextchief">Nächst höhere/r Vorgesetzte/r</prop>
        <prop mnemo="datevisa">Datum/Visum</prop>
    </local>
    <local scope="DUTY_VALIDITY" alias="DUTY_VALIDITY_V"></local>

    <local scope="reportLayout">
        <prop mnemo="JobDescriptionAllExcelHeader">Stellenbeschreibungen</prop>
        <prop mnemo="JobDescriptionAllExcelOeTitle">Organisationseinheit</prop>
        <prop mnemo="JobDescriptionAllExcelJobTitle">Stellenbezeichnung</prop>
        <prop mnemo="JobDescriptionAllExcelPersonnelnumber">Personalnr.</prop>
        <prop mnemo="JobDescriptionAllExcelName">Name</prop>
        <prop mnemo="JobDescriptionAllExcelFirstname">Vorname</prop>
        <prop mnemo="JobDescriptionAllExcelLastChange">Letzte Änderung</prop>
    </local>

    <local scope="DUTY_VALIDITY_V">
 		<prop mnemo="NUMBER">Numéro</prop>
 		<prop mnemo="TITLE_FR">Désignation</prop>
    <prop mnemo="WEIGHTING">Gewichtung</prop>
 		<prop mnemo="DESCRIPTION_FR" size="80,8">Description</prop>
	 	<prop mnemo="VALID_FROM">Valable de</prop>
	 	<prop mnemo="VALID_TO">Valable à</prop>
    </local>
    <local scope="DUTY_COMPETENCE__DUTY_VALIDITY_V" alias="DUTY_COMPETENCE_VALIDITY"></local>
    <local scope="DUTY_COMPETENCE_VALIDITY">
        <prop mnemo="VALID_FROM">Valable de</prop>
        <prop mnemo="VALID_TO">Valable à</prop>
    </local>
    <local scope="FUNCGROUPV">
        <prop mnemo="PERSON_ID">Collaborateur</prop>
    </local>
</map>

=== Steinacher62/p-soft/Knowledge/XML/language_EN.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="knowledge">WISSEN</prop>
    </local>
    <local scope="tableName">
 		<prop mnemo="KNOWLEDGE_V">Wissen</prop>
 		<prop mnemo="KNOWLEDGE">Wissen</prop>
 		<prop mnemo="THEME">Thema</prop>
    </local>
    <local scope="knowledge">
        <prop mnemo="knowledge">Wissen</prop>
        <prop mnemo="miSearchKnowledge">Wissen suchen</prop>
        <prop mnemo="miNewKnowledge">Neues globales Wissenselement</prop>
        <prop mnemo="miPrintKnowledge">Wissen drucken</prop>
        <prop mnemo="bcSearchKnowledge">Wissen suchen</prop>
        <prop mnemo="bcPrintKnowledge">Print Knowledge</prop>
        <prop mnemo="bcEditTheme">Thema bearbeiten</prop>
        <prop mnemo="bcAddTheme">Thema hinzufügen</prop>
        <prop mnemo="bcEditKnowledge">Wissenselement bearbeiten</prop>
        <prop mnemo="bcAddKnowledge">Globales Wissenselement hinzufügen</prop>
        <prop mnemo="ctContents">Inhaltsverzeichnis</prop>
        <prop mnemo="ctKnowledge">Wissenselement</prop>
        <prop mnemo="ctAssignedKnowledges">Verknüpftes Wissen</prop>
        <prop mnemo="ctAdministration">Administration</prop>
        <prop mnemo="clEditKnowledge">Wissenselement bearbeiten</prop>
        <prop mnemo="clNewKnowledge">Mit neuem Wissenselement verknüpfen</prop>
        <prop mnemo="clDeleteKnowledge">Wissenselement löschen</prop>
        <prop mnemo="clAddTheme">Neues Thema</prop>
        <prop mnemo="clAddDocument">Neues Dokument</prop>
        <prop mnemo="clAddImage">Neues Bild</prop>
        <prop mnemo="clInviteAuthors">Autoren einladen</prop>
        <prop mnemo="stDocuments">Dokumente</prop>
        <prop mnemo="stRegistry">Registratur</prop>
        <prop mnemo="bcEditHistory">Bemerkung bearbeiten</prop>
        <prop mnemo="bcAddHistory">Neue Version erstellen</prop>
        <prop mnemo="ttGenerateWordDocument">Word Dokument erzeugen...</prop>
        <prop mnemo="btPrintSelection">Print Selection</prop>
        <prop mnemo="cbKnowledgeOnly">Nur Wissenelemente listen</prop>
        <prop mnemo="popupCannotDeleteKnowledge">Warnung: Das Wissenelement kann nicht gelöscht werden</prop>
        <prop mnemo="stSuggestionRanking">Bewertung des Vorschlags</prop>
        <prop mnemo="ttAndOder">Titel mit Thementyp mit&#13;&#10;- 'und' oder,&#13;&#10;- 'oder'&#13;&#10;verkn&#252;pfen</prop>
        <prop mnemo="columnKnowledgeTitle">Wissenelement Titel</prop>
    </local>
    <local scope="KNOWLEDGE_V" alias="KNOWLEDGE"></local>
    <local scope="KNOWLEDGE">
        <prop mnemo="TITLE_EN" size="80,1">Titel</prop>
        <prop mnemo="DESCRIPTION_EN" size="100,25">Beschreibung</prop>
        <prop mnemo="CREATED_EN">Erstellt am</prop>
        <prop mnemo="CREATOR_PERSON_ID_EN">Erstellt durch</prop>
        <prop mnemo="TRIGGER_UID">Quelle</prop>
        <prop mnemo="THEMETYPE_ID_EN" size="80,1">Thementyp</prop>
        <prop mnemo="TYPE" size="80,1">Typ</prop>
        <prop mnemo="ISACTIVE" size="80,1">Bewertung</prop>
        <prop mnemo="SUGGESTION_EXECUTION_ID" size="80,1">Vorschlag</prop>
        <prop mnemo="SUGGESTION_STATI_ID" size="80,1">Bewertung</prop>
        <enum name="types">
            <prop mnemo="0">Default</prop>
            <prop mnemo="1">Vorschlag</prop>
        </enum>
        <enum name="isActiveSuggestion">
            <prop mnemo="0">Inaktive Vorschläge</prop>
            <prop mnemo="1">Aktive Vorschläge</prop>
        </enum>        
    </local>
    <local scope="THEME">
        <prop mnemo="TITLE_DE" size="80,1">Wissenelement Titel</prop>
        <prop mnemo="TITLE" size="80,1">Theme Titel</prop>
        <prop mnemo="DESCRIPTION" size="100,25">Beschreibung</prop>
        <prop mnemo="CREATED">Erstellt am</prop>
        <prop mnemo="CREATOR_PERSON_ID">Erstellt durch</prop>
        <prop mnemo="ORDNUMBER">Position</prop>
    </local>
</map>

=== Steinacher62/p-soft/RSR/XML/language_FR.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="rsr">RÉMUNÉRATION</prop>
    </local>
    <local scope="rsr">
        <prop mnemo="salaryChangePercentage">Augmentation salaire %</prop>
        <prop mnemo="salaryPercentageOfProposed">% d'atteinte fonction clé</prop>
        <prop mnemo="proposedSalaryDifference">Diff. réel et fonction en Frs</prop>
        <prop mnemo="proposedSalaryPercentageDifference">Diff. réel et fonction en %</prop>
        <prop mnemo="salaireBudgetAllocation">Budget pour modification des salaires</prop>
        <prop mnemo="primeBudgetAllocation">Budget pour primes</prop>
        <prop mnemo="salaireadjustment">Modification des salaires</prop>
        <prop mnemo="primeadjustment">Entrer des primes</prop>
        <prop mnemo="salaireApprovement">Approuvement des salaires</prop>
        <prop mnemo="primeApprovement">Approuvement des primes</prop>
        <prop mnemo="salaireBudgetCheck">Contrôle de budget pour salaire</prop>
        <prop mnemo="primeBudgetCheck">Contrôle de budget pour prime</prop>
        <prop mnemo="salaireoverview">Aperçu des salaires</prop>
        <prop mnemo="primeoverview">Aperçu des primes</prop>
        <prop mnemo="salaireExport">Exportation des salaires</prop>
        <prop mnemo="primeExport">Exportation des primes</prop>
        <prop mnemo="salarySituation">Situation salariale #1</prop>
        <prop mnemo="situation">Situation #1</prop>
        <prop mnemo="salaireLink">Modification d. salaires</prop>
        <prop mnemo="primeLink">Primes</prop>
        <prop mnemo="prime">Prime</prop>
    </local>
    <local scope="PERSON">
        <prop mnemo="AGE">Age</prop>
    </local>
    <local scope="FUNKTION">
        <prop mnemo="TITLE_FR_REP">Fonction indemnisée</prop>
    </local>
    <local scope="EMPLOYMENT">
        <prop mnemo="EMPLOYMENTTYP">Statut de salariés</prop>
        <prop mnemo="EMPLOYMENTKIND">Type de contrat</prop>
        <prop mnemo="COSTCENTER_NUMBER">Centre de coût</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Centre de coût</prop>
        <prop mnemo="SUPERIOR">Supérieur hiérarchique</prop>
    </local>
    <local scope="RSR_LOHNDATEN_V" alias="LOHN">
        <prop mnemo="PNAME">Nom</prop>
        <prop mnemo="FIRSTNAME">Prénom</prop>
        <prop mnemo="ENTRY">Date d'entrée RSR</prop>
        <prop mnemo="AGE">Age</prop>
        <prop mnemo="TITLE_DE">Emploi</prop>
        <prop mnemo="ENGAGEMENT">Temps de travail</prop>
        <prop mnemo="EMPLOYMENTTYP">Statut de salariés</prop>
        <prop mnemo="EMPLOYMENTKIND">Type de contrat</prop>
        <prop mnemo="COSTCENTER_NUMBER">Centre de coût</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Centre de coût</prop>
        <prop mnemo="SUPERIOR">Supérieur hiérarchique</prop>
        <prop mnemo="SALAIRE">Augmentation salaire Frs</prop>
        <prop mnemo="PRIME">Prime</prop>
        <prop mnemo="INDEMNITE_DE_FONCTION">Indemnité de fonction</prop>
        <prop mnemo="FORFAIT_B">Forfaits B</prop>
        <prop mnemo="ISTLOHN">Salaire réel</prop>
        <prop mnemo="LOHNVORSCHLAG">Salaire fonction</prop>
    	<prop mnemo="NEUER_LOHN">Nouveau salaire</prop>
        <prop mnemo="KOMMENTARS">Commentaire salaire</prop>
        <prop mnemo="KOMMENTARP">Commentaire Prime</prop>
        <prop mnemo="INFORMATIONP">Information Prime</prop>
        <prop mnemo="INFORMATIONS">Kommentar salaire</prop>
        <prop mnemo="REPRICHTLOHN">salaire de référence fct indemnisée</prop>
   </local>
    <local scope="RSR_LISTE_V" alias="PERSON">
        <prop mnemo="TITLE_FR">Fonction</prop>
        <prop mnemo="BUDGETTYP_ID">Budget</prop>
        <prop mnemo="EMPLOYMENTTYP">Statut de salariés</prop>
        <prop mnemo="EMPLOYMENTKIND">Type de contrat</prop>
        <prop mnemo="COSTCENTER_NUMBER">Centre de coût</prop>
        <prop mnemo="COSTCENTER_DESCRIPTION">Centre de coût</prop>
        <prop mnemo="SUPERIOR">Supérieur hiérarchique</prop>
    	<prop mnemo="ISTLOHN">Salaire réel</prop>
    	<prop mnemo="NEUER_LOHN">Nouveau salaire année</prop>
    	<prop mnemo="RICHTLOHN">Salaire fonction</prop>
    	<prop mnemo="LOHNVORSCHLAG">Salaire fonction</prop>
    	<prop mnemo="ZUNAHME_PROZENT">% d'augmen-tation</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Statut</prop>
        <prop mnemo="BETRAG">Mesure salariale Année Frs</prop>
        <prop mnemo="BETRAG_PRO_STUNDE">Mesure salariale Horaire Frs</prop>
        <prop mnemo="ISTLOHN_PROZENT">% d'atteinte du salaire de fonction</prop>
    	<prop mnemo="NEUER_LOHN_PRO_ISTLOHN">%</prop>
    	<prop mnemo="NEUER_STUNDENLOHN">Nouveau salaire horaire</prop>
    	<prop mnemo="NEUER_LOHN_PROZENT">% d'atteinte fonction clé</prop>
        <prop mnemo="KOMMENTARS">Commentaire</prop>
        <prop mnemo="KOMMENTARP">Commentaire</prop>
        <prop mnemo="ENGAGEMENT">Temps de travail</prop>
        <prop mnemo="VERGLEICH">Comparatif salaire horaire</prop>
    </local>
    <local scope="SALAIRE" alias="RSR_LISTE_V">
    </local>
    <local scope="PRIME" alias="RSR_LISTE_V">
    </local>
    <local scope="OVERVIEW_SALAIRE" alias="RSR_LISTE_V">
    </local>
    <local scope="OVERVIEW_PRIME" alias="RSR_LISTE_V">
    </local>
</map>
