=== Steinacher62/p-soft/XML/dtd/language.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT map (global?, local*)>
<!ELEMENT global (prop | enum)*>
<!ELEMENT local (prop | enum)*>
<!ELEMENT enum (prop+)>
<!ELEMENT prop (#PCDATA)>
<!ATTLIST local 
    scope CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ATTLIST prop 
   mnemo CDATA #REQUIRED
   size CDATA "-1,-1"
>
<!ATTLIST enum name CDATA #REQUIRED>

=== Steinacher62/p-soft/Habasit/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="habasit">HABASIT</prop>
    </local>    
    <local scope="habasit">
        <prop mnemo="reportAveragePerformance">Leistungsbewertung</prop>
        <prop mnemo="reportDate">Datum</prop>
        <prop mnemo="reportSign">K&#252;rzel/Unterschrift</prop>
        <prop mnemo="reportSupervisor">Vorgesetzter</prop>
        <prop mnemo="reportClerk">Mitarbeiter</prop>
        <prop mnemo="reportSupervisorRating">Leistungsbewertung</prop>
        <prop mnemo="reportClerkRating">Selbstbewertung</prop>
        <prop mnemo="reportRatingDate">Datum Leistungsbewertung</prop>
        <prop mnemo="reportHigherSupervisor">H&#246;herer Vorgesetzter</prop>
        <prop mnemo="reportEmplRemarks">Bemerkungen des Mitarbeiters</prop>
    </local>
</map>

=== Steinacher62/p-soft/SBS/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="sbs">
        <prop mnemo="sbs">Swiss Board School</prop>
        <prop mnemo="addEditUser">Benutzer Verwalten</prop>
        <prop mnemo="userManagement">Benutzerverwaltung</prop>
        <prop mnemo="seminarManagement">Seminare Verwalten</prop>
        <prop mnemo="addEditSeminar">Seminarverwaltung</prop>
        <prop mnemo="startPage">Startseite</prop>

    </local>
    <local scope="navigation">
        <prop mnemo="addUser">Benutzer hinzufügen</prop>
    </local>
   
</map>

=== Steinacher62/p-soft/Lohn/XML/language_EN.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="lohn">LOHN</prop>
    </local>
    <local scope="lohn">
        <prop mnemo="division">Division</prop>
        <prop mnemo="budgetComp">Budget Equation</prop>
        <prop mnemo="clear">Release</prop>
        <prop mnemo="clearAll">Alle Freigeben</prop>
        <prop mnemo="clearAllocationAll">Alle Verteilungen Freigeben</prop>
        <prop mnemo="print">Drucken</prop>
        <prop mnemo="previous">Vorheriges</prop>
        <prop mnemo="history">Vorjahre</prop>
        <prop mnemo="next">Nächstes</prop>
        <prop mnemo="terminate">Terminate</prop>
        <prop mnemo="terminatePrompt">Termination Prompt</prop>
        <prop mnemo="admin">Stati administrieren</prop>
        <prop mnemo="importExport">Import from and Export to OGS System</prop>
        <prop mnemo="import">Start Import</prop>
        <prop mnemo="dbNameLabel">OGS Database</prop>
        <prop mnemo="budgetConfirmation">The changes were applied to all employees. Are you sure you want to proceed?</prop>
        <prop mnemo="hours">hours</prop>
        <prop mnemo="days">days</prop>
        <prop mnemo="months">months</prop>
        <prop mnemo="showAll">Show all</prop>
        <prop mnemo="showAlladjustment">Alle anzeigen</prop>
        <prop mnemo="showAlloverview">Alle ab dieser OE</prop>
        <prop mnemo="exportExcel">Export Excel</prop>
        <prop mnemo="budgetGroup">Budget allocation</prop>
        <prop mnemo="editingGroup">Measures</prop>
        <prop mnemo="genehmigungGroup">Approvement</prop>
        <prop mnemo="budgetCheckGroup">Budget check</prop>
        <prop mnemo="overviewGroup">Overview</prop>
        <prop mnemo="administrationGroup">Administration</prop>
        <prop mnemo="importExportLink">Import/Export</prop>
        <prop mnemo="shortDay">D</prop>
        <prop mnemo="subOE">Direkt unterstellte OE's</prop>
        <prop mnemo="genehmigenTitle">Approve</prop>
        <prop mnemo="resetTitle">Edit</prop>
        <prop mnemo="differenzVerteilbar">Differenz verteilbar</prop>
        <prop mnemo="differenzVerfuegbar">Differenz verfügbar</prop>
        <prop mnemo="loadAllOK">Vollständiger Import der Daten erfolgreich abgeschlossen</prop>
        <prop mnemo="loadAllError">Vollständiger Import der Daten fehlgeschlagen (siehe Log-file)</prop>
        <prop mnemo="approveAll">Alles genehmigen</prop>
        <prop mnemo="approve">Genehmigen</prop>
        <prop mnemo="closeApprove">Abschliessen/Genehmigen</prop>
        <prop mnemo="komponente">Lohnkomponente</prop>
        <prop mnemo="with">Mit</prop>
        <prop mnemo="without">Ohne</prop>
        <enum name="genehmigenValue">
            <prop mnemo="0"></prop>
            <prop mnemo="1">approve</prop>
            <prop mnemo="2">reset</prop>
        </enum>
        <enum name="resetValue">
            <prop mnemo="0"></prop>
            <prop mnemo="1">again</prop>
        </enum>
        <enum name="salaryType">
            <prop mnemo="1">Annual wage</prop>
            <prop mnemo="2">Monthly wage</prop>
            <prop mnemo="3">Daily wage</prop>
            <prop mnemo="4">Hourly wage</prop>
        </enum>
        <enum name="editingState">
            <prop mnemo="0">pending</prop>
            <prop mnemo="1">done</prop>
            <prop mnemo="2">approved</prop>
        </enum>
        <enum name="clearingState">
            <prop mnemo="0">disabled</prop>
            <prop mnemo="1">Allocation enabled</prop>
            <prop mnemo="2">enabled</prop>
        </enum>
    </local>
    <local scope="KOMPONENTE">
    	<prop mnemo="BEZEICHNUNG">Bezeichnung</prop>
    	<prop mnemo="BUDGET">Gesamtbudget</prop>
    	<prop mnemo="BUDGET_IN_PROZENT">Budget in %</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
    </local>
    <local scope="BUDGET">
    	<prop mnemo="BETRAG">Budget</prop>
    	<prop mnemo="BETRAG_VERTEILBAR">Verteilbares Budget</prop>
    	<prop mnemo="KOMPONENTE_ID">Komponente</prop>
    	<prop mnemo="ORGENTITY_ID">OE</prop>
    	<prop mnemo="BUDGETTYP_ID">Budgettyp</prop>
    </local>
    <local scope="LOHNKOMPONENTE">
    	<prop mnemo="BETRAG">Anpassung pro Jahr in CHF</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">State</prop>
    	<prop mnemo="KOMPONENTE_ID">Komponente</prop>
    	<prop mnemo="LOHN_ID">Lohn</prop>
    	<prop mnemo="BUDGET_ID">Budget</prop>
    </local>
    <local scope="LOHN">
    	<prop mnemo="LOHNART">Lohnart</prop>
    	<prop mnemo="ANZAHL_LOEHNE">Anzahl L&#246;hne</prop>
    	<prop mnemo="ANZAHL_STUNDEN">Anzahl Stunden</prop>
    	<prop mnemo="ANZAHL_TAGE">Anzahl Tage</prop>
    	<prop mnemo="ISTLOHN">Istlohn pro Jahr</prop>
    	<prop mnemo="NEUER_LOHN">Neuer Lohn pro Jahr</prop>
    	<prop mnemo="RICHTLOHN">Richtlohn pro Jahr</prop>
    	<prop mnemo="LOHNVORSCHLAG">Lohnvorschlag pro Jahr</prop>
    	<prop mnemo="AUSSCHLUSS_LOHN">Ausschluss Lohn</prop>
    	<prop mnemo="AUSSCHLUSS">Ausschluss Berechnung</prop>
    	<prop mnemo="AUSSCHLUSS_BIS">Ausschluss bis</prop>
    	<prop mnemo="BERECHNUNG_ERFOLGREICH">Berechnung erfolgreich</prop>
    	<prop mnemo="GRUND">Fehler</prop>
    	<prop mnemo="HERANFUEHRUNG">Heranf&#252;hrung ber&#252;cksichtigen</prop>
        <prop mnemo="INFORMATION">Information</prop>
        <prop mnemo="KOMMENTAR">Kommentar</prop>
        <prop mnemo="KOMMENTARL">Kommentar Lohn</prop>
    	<prop mnemo="VARIANTE_ID">Variante</prop>
    	<prop mnemo="EMPLOYMENT_ID">Anstellung</prop>
    </local>
    <local scope="EMPLOYMENT_PERSON_OE_V" alias="PERSON">
    	<prop mnemo="OE_TITLE_EN">Zust&#228;ndige OE</prop>
    	<prop mnemo="TITLE_EN">Anstellung</prop>
    	<prop mnemo="ENGAGEMENT">Besch&#228;ftigungsgrad</prop>
    </local>
    <local scope="EMPLOYMENT">
    	<prop mnemo="ORGENTITY_ID">F&#252;r Lohn zust&#228;ndige OE</prop>
    	<prop mnemo="BUDGETTYP_ID">Budgettyp</prop>
    </local>
    <local scope="DLA_ORGENTITY_V" alias="ORGENTITY">
        <prop mnemo="FUNKTION_TITLE">Function</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Status</prop>
        <prop mnemo="FREIGABESTATUS">Clearing</prop>
        <prop mnemo="ABWEICHUNG">Positive Abw.</prop>
        <prop mnemo="VERTEILBAR">Verteilbar</prop>
        <prop mnemo="VERFUEGBAR">Verfügbar</prop>
        <prop mnemo="VERTEILT">Verteilt</prop>
        <prop mnemo="DIFFERENZ">Differenz</prop>
    	<prop mnemo="BUDGETTYP">Budget type</prop>
        <prop mnemo="AUFWAND">Cost</prop>
        <prop mnemo="PNAME">Chef</prop>
   </local>
    <local scope="BUDGET_V">
        <prop mnemo="TITLE_EN">Division</prop>
    	<prop mnemo="BETRAG">Budget</prop>
    	<prop mnemo="BETRAG_VERTEILBAR">Distributable Budget</prop>
    	<prop mnemo="KOMPONENTE">Component</prop>
    	<prop mnemo="ORGENTITY_ID">Division</prop>
    	<prop mnemo="BUDGETTYP">Budget type</prop>
        <prop mnemo="BEARBEITUNGSSTATUS">Editing state</prop>
        <prop mnemo="FREIGABESTATUS">Clearing state</prop>
        <prop mnemo="AUFWAND">Cost</prop>
        <prop mnemo="DIFFERENZ">Difference</prop>
        <prop mnemo="KOMP_BEZEICHNUNG">Komponente</prop>
    </local>
</map>

=== Steinacher62/p-soft/Suggestion/XML/language_FR.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="suggestion">VORSCHLAGSWESEN</prop>
    </local>
    <local scope="SUGGESTION">
 		<prop mnemo="TITLE_DE">Bezeichnung</prop>
 		<prop mnemo="DESCRIPTION_DE">Beschreibung</prop>
	 	<prop mnemo="CREATED">Kreiert</prop>
	 	<prop mnemo="ISPUBLIC">Öffentlich</prop>
	 	<prop mnemo="ISACTIVE">Vorschlagswesen Status</prop>
    </local>
    <local scope="SUGGESTION_STEP">
 		<prop mnemo="TITLE_DE">Bezeichnung</prop>
 		<prop mnemo="DESCRIPTION_DE" size="50,5">Beschreibung</prop>
    </local>
    <local scope="SUGGESTION_QUESTION">
 		<prop mnemo="TITLE_DE">Bezeichnung</prop>
 		<prop mnemo="QUESTION_DE">Frage</prop>
	 	<prop mnemo="TYP">Typ</prop>
	 	<prop mnemo="ANSWERREQUIRED">Pflichtantwort</prop>
	 	<prop mnemo="DATE_MIN">Datumsbereich ab</prop>
	 	<prop mnemo="DATE_MAX">Datumsbereich bis</prop>
	 	<prop mnemo="NUMBER_MIN">Zahlenbereich ab</prop>
	 	<prop mnemo="NUMBER_MAX">Zahlenbereich bis</prop>
	 	<prop mnemo="CHARS_MIN">Min. Anzahl Zeichen</prop>
	 	<prop mnemo="CHARS_MAX">Max. Anzahl Zeichen</prop>
 		<prop mnemo="RESOLUTION_TEXT_DE">Lösung</prop>
	 	<prop mnemo="RESOLUTION_DATE">Lösung</prop>
	 	<prop mnemo="RESOLUTION_NUMBER">Lösung</prop>
	 	<prop mnemo="RESOLUTION_BOOLEAN">Lösung</prop>
	 	<prop mnemo="RESOLUTION_COMMENT_DE">Lösungskommentar</prop>
    </local>
    <local scope="SUGGESTION_ANSWEROPTION">
 		<prop mnemo="LABEL_DE">Bezeichnung</prop>
	 	<prop mnemo="VALUE_DE">Rückgabewert</prop>
	 	<prop mnemo="ISRESOLUTION">Ist richtige Antwort</prop>
    </local>
    <local scope="SUGGESTION_EXECUTION">
 		<prop mnemo="TITLE">Bezeichnung</prop>
 		<prop mnemo="CREATED">Datum</prop>
	 	<prop mnemo="PERSON_ID">Benutzer</prop>
	 	<prop mnemo="SURVEY_ID">Vorschlagswesen</prop>
	 	<prop mnemo="ISFINISHED">Status</prop>
    </local>

    <local scope="suggestion">
	 	<prop mnemo="suggestion">Vorschlagswesen</prop>
	 	<prop mnemo="step">Schritt</prop>
	 	<prop mnemo="nextStep">Nächster Schritt &gt;&gt;</prop>
	 	<prop mnemo="previousStep">&lt;&lt; Vorheriger Schritt</prop>
	 	<prop mnemo="finish">Vorschlag zwischenspeichern</prop>
        <prop mnemo="sendToKnowledge">Vorschlag einreichen</prop>
	 	<prop mnemo="noExecutionTitle">Unbekannt</prop>
	 	<prop mnemo="subNavTitle">Vorschagswesen</prop>
	 	<prop mnemo="subNavSearchSuggestion">Vorschagswesen suchen</prop>
        <prop mnemo="subNavOwnSuggestionExecutions">Eigene Vorschläge</prop>
        <prop mnemo="subNavAllSuggestionExecutions">Alle Vorschläge</prop>	 	
        <prop mnemo="subNavAllSuggestionExecutionsMatrix">Vorschlägematrix</prop>        	 	
	 	<prop mnemo="valAnswerRequired">Bitte beantworten Sie diese Frage!</prop>
	 	<prop mnemo="valOutOfRange">Eingabe liegt ausserhalb des gültigen Bereichs.</prop>
	 	<prop mnemo="valRangeTextMin">Der eingegebene Text muss mindestens #1 Zeichen enthalten.</prop>
	 	<prop mnemo="valRangeTextMax">Der eingegebene Text darf maximal #1 Zeichen enthalten.</prop>
	 	<prop mnemo="valRangeTextMinMax">Der eingegebene Text muss zwischen #1 und #2 Zeichen enthalten.</prop>
	 	<prop mnemo="valRangeNumberMin">Die eingegebene Zahl muss grösser als #1 sein.</prop>
	 	<prop mnemo="valRangeNumberMax">Die eingegebene Zahl darf nicht grösser als #1 sein.</prop>
	 	<prop mnemo="valRangeNumberMinMax">Die eingegebene Zahl muss zwischen #1 und #2 sein.</prop>
	 	<prop mnemo="valInfoRangeNumberMinMax">Zahl zwischen #1 und #2</prop>
	 	<prop mnemo="valInfoRangeNumberMin">Zahl ab #1</prop>
	 	<prop mnemo="valInfoRangeNumberMax">Zahl bis #1</prop>	 	
	 	<prop mnemo="valRangeDateMin">Das eingegebene Datum muss nach #1 sein.</prop>
	 	<prop mnemo="valRangeDateMax">Das eingegebene Datum darf nicht nach #1 sein.</prop>
	 	<prop mnemo="valRangeDateMinMax">Das eingegebene Datum muss zwischen #1 und #2 sein.</prop>
	 	<prop mnemo="valInfoRangeDateMinMax">Datum zwischen #1 und #2</prop>	 	
	 	<prop mnemo="valInfoRangeDateMin">Datum ab #1</prop>	 	
	 	<prop mnemo="valInfoRangeDateMax">Datum bis #1</prop>	 		 	
	 	<prop mnemo="bcSearchSuggestion">Vorschagswesen suchen</prop>
	 	<prop mnemo="ctSuggestionSearchresult">Folgende Vorschagswesen wurden gefunden:</prop>
	 	<prop mnemo="ctSuggestionSelection">Vorschagswesen gemäss Selektion:</prop>
	 	<prop mnemo="ctExecutableSuggestions">Von #1 durchführbare Vorschagswesen:</prop>
	 	<prop mnemo="ctSuggestionExecutions">#1</prop>
	 	<prop mnemo="ctExecutionSelection">Durchführungen gemäss Selektion:</prop>
	 	<prop mnemo="cmExecuteSuggestion">Vorschlag erfassen</prop>
	 	<prop mnemo="cmShowExecutions">Durchführungen anzeigen</prop>
	 	<prop mnemo="cmtSelectedSuggestion">Vorschlagswesen</prop>
	 	<prop mnemo="cmtListedSuggestions">Vorschagswesen in Liste</prop>
	 	<prop mnemo="labelFreeText">Antwort</prop>
        <prop mnemo="labelYesOrNo">Ja/Nein</prop>
        <prop mnemo="labelDate">Datum</prop>
        <prop mnemo="labelNumber">Nummer</prop>
        <prop mnemo="textCreatorPerson">Erstellt durch</prop>
        <prop mnemo="cmLinkToKnowledge">Wissenselement</prop>
        <prop mnemo="deleteSuggKnow">Löschen des Vorschlags und des Wissenselements</prop>
        <prop mnemo="ciNoActiveSuggestionFound">Zurzeit ist kein Vorschlagswesen aktiv</prop>
        <prop mnemo="ciNoActiveSubmittedExecutionFound">Es sind zurzeit keine eingereichten Vorschläge vorhanden.</prop>
        <prop mnemo="ttMatrixTitle">Titel</prop>
        <prop mnemo="ttMatrixDate">Erfasst</prop>
        <prop mnemo="ttMatrixRating">Bewertung</prop>
        <prop mnemo="ttMatrixRemark">Bemerkung zur Bewertung</prop> 
        <prop mnemo="btnGenerateExcelFile">Excel Datei erzeugen</prop>               
        <enum name="finishedEnum">
            <prop mnemo="0">In Bearbeitung</prop>
            <prop mnemo="1">Gespeichert (noch nicht gesendet)</prop>
            <prop mnemo="2">Gesendet</prop>
        </enum> 
    </local>
    <local scope="suggestion_execution">
	 	<prop mnemo="stateNew">In Bearbeitung</prop>
	 	<prop mnemo="stateComplete">Gespeichert (noch nicht gesendet)</prop>
	 	<prop mnemo="stateSent">Gesendet</prop>	 	
	</local>
</map>

=== Steinacher62/p-soft/Subscription/XML/language_EN.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="subscription">Abonnement</prop>
    </local>
    <local scope="navigation">
    </local>
    <!-- Subscription -->
    <local scope="SUBSCRIPTION">
        <prop mnemo="ID">ID</prop>
 		<prop mnemo="TITLE">Name</prop>
 		<prop mnemo="VALID_FROM">Valid from</prop>
 		<prop mnemo="VALID_TO">Valid until</prop>
 		<prop mnemo="PERSON_ID">Abonnent</prop>
 		<prop mnemo="EVENTS">Ereignisse</prop>
 		<prop mnemo="ACTIVE">Aktiv</prop>
 		<prop mnemo="EMAILENABLE">Nachricht per EMail</prop>
 		<prop mnemo="EMAIL">EMail</prop>
 		<prop mnemo="TRIGGER_ID">Trigger</prop>
    </local>
    <!-- News -->
    <local scope="NEWS">
 		<prop mnemo="TITLE_DE">Bezeichnung</prop>
 		<prop mnemo="TITLE_FR">Bezeichnung</prop>
 		<prop mnemo="TITLE_IT">Bezeichnung</prop>
 		<prop mnemo="TITLE_EN">Bezeichnung</prop>
 		<prop mnemo="DESCRIPTION_DE" size="80,8">Beschreibung</prop>
 		<prop mnemo="DESCRIPTION_FR" size="80,8">Beschreibung</prop>
 		<prop mnemo="DESCRIPTION_IT" size="80,8">Beschreibung</prop>
 		<prop mnemo="DESCRIPTION_EN" size="80,8">Beschreibung</prop>
 		<prop mnemo="CREATED">Erstellt</prop>
 		<prop mnemo="VALID_FROM">Gültig ab</prop>
 		<prop mnemo="VALID_TO">Gültig bis</prop>
 		<prop mnemo="VISIBILITY">Sichtbar</prop>
 		<prop mnemo="URL">URL</prop>
 		<prop mnemo="TARGET">Target</prop>
 		<prop mnemo="URL_TEXT_DE">URL-Text</prop>
 		<prop mnemo="URL_TEXT_FR">URL-Text</prop>
 		<prop mnemo="URL_TEXT_IT">URL-Text</prop>
 		<prop mnemo="URL_TEXT_EN">URL-Text</prop>
    </local>
    <local scope="news">
    	<prop mnemo="EDIT">Bearbeitet: </prop>
    	<prop mnemo="DELETE">Gelöscht: </prop>
    	<prop mnemo="NEW">Neu: </prop>
    	<prop mnemo="NEWS">Meldungen</prop>
    	<prop mnemo="SUBSCRIPTION">Abonnement</prop>
    	<prop mnemo="DOCUMENT">Dokument</prop>
    	<prop mnemo="FOLDER">Ordner</prop>
    	<prop mnemo="CLIPBOARD">Ablage</prop>
    	<prop mnemo="FORUM">Forum</prop>
    	<prop mnemo="TOPIC">Beitrag</prop>
    	<prop mnemo="LINK">Querverweis</prop>
    	<prop mnemo="CONTRIBUTION">Anmerkung</prop>
    	<prop mnemo="DOCUMENT_LINK">Verknüpfung</prop>
    	<prop mnemo="TASKLIST">Pendenzenliste</prop>
    	<prop mnemo="MEASURE">Pendenz</prop>
    	<prop mnemo="KNOWLEDGE">Wissen</prop>
    	<prop mnemo="by"> durch </prop>
    	<prop mnemo="new">Meldung</prop>
    	<prop mnemo="news">Meldungen</prop>
    	<prop mnemo="subscription">Abonnement</prop>
    	<prop mnemo="subscriptions">Abonnemente</prop>
    	<prop mnemo="editNEWS">Meldung bearbeiten</prop>
    	<prop mnemo="addNEWS">Neue Meldung</prop>
    	<prop mnemo="editSUBSCRIPTION">Abonnement bearbeiten</prop>
    	<prop mnemo="addSUBSCRIPTION">Neues Abonnement</prop>
    	<prop mnemo="detailSUBSCRIPTION">Detail Abonnement</prop>
 		<prop mnemo="deleteNEWSConfirm">Meldung löschen?</prop>
 		<prop mnemo="deleteSUBSCRIPTIONConfirm">Abonnement löschen?</prop>
 		<prop mnemo="invalidSubscription">Ungültiges Abonnement</prop>
 		<prop mnemo="inactiveSubscription">Abonnement nicht aktiv</prop>
 		<prop mnemo="activeSubscription">Aktives Abonnement</prop>
 		<prop mnemo="emailSubject">Änderungsmeldung</prop>
 		<prop mnemo="emailComment">Der p-soft Benachrichtigungsdienst hat folgende für Sie relevante Änderung in einem der Inhalte festgestellt:</prop>
    </local>
    <local scope="error">
        <prop mnemo="dispatchNotAviable">Die Email-Funktion steht nicht zur Verfügung.</prop>
    </local>
</map>

=== Steinacher62/p-soft/Kaiser/XML/language_DE.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
  <local scope="morph">
    <prop mnemo="bcSearchMatrix">Karte suchen</prop>
    <prop mnemo="bcSearchSlave">Detail Karte suchen</prop>
    <prop mnemo="bcMatrixList">Liste Karten</prop>
    <prop mnemo="bcSlaveList">Liste detail Karte</prop>
    <prop mnemo="myProducts">Meine Karten</prop>
  </local>
  <local scope="matrix">
    <prop mnemo="newMap">Neue Karte erstellen</prop>
    <prop mnemo="copyMap">Karte kopieren</prop>
    <prop mnemo="deleteMap">Karte löschen</prop>
    <prop mnemo="printMap">Karte drucken</prop>
    <prop mnemo="changeMap">Andere Karte öffnen (Ctrl + M)</prop>
    <prop mnemo="insertSokratesFollowing">Nachfolgend Zelle einfügen</prop>
    <prop mnemo="insertSokratesPrevious">Vorhergehend Zelle einfügen</prop>
    <prop mnemo="removeCell">Zelle löschen</prop>
    <prop mnemo="joinFollowingSokrateselement">Mit unterer Zelle verbinden</prop>
    <prop mnemo="separateSokrateselement">Zelle auftrennen</prop>
    <prop mnemo="deleteCellConfirm">Wollen Sie die Zelle wirklich löschen?</prop>
    <prop mnemo="deleteRowConfirm">Wollen Sie die Zeile wirklich löschen?</prop>
  </local>
</map>

=== Steinacher62/p-soft/Dispatch/XML/language_EN.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE map SYSTEM "../../XML/dtd/language.dtd" >
<map>
    <!-- ä &#228; ö &#246; ü &#252; Ä &#196; Ö &#214; Ü &#220; <b> &lt;b&gt; </b> &lt;/b&gt; -->
    <local scope="ModuleNames">
        <prop mnemo="dispatch">VERSAND</prop>
    </local>
    <local scope="dispatch">
        <prop mnemo="LabelTarget">Einträge:</prop>
        <prop mnemo="selectTarget">Auswählen...</prop>
        <prop mnemo="targetAll">Alle</prop>
        <prop mnemo="targetSelection">Ausgewählte</prop>
        <prop mnemo="LabelFrom">Von:</prop>
        <prop mnemo="LabelTo">An:</prop>
        <prop mnemo="LabelSubject">Betreff:</prop>
        <prop mnemo="LabelTemplates">Vorlagen:</prop>
        <prop mnemo="LabelMailTemplates">EMail-Vorlage:</prop>
        <prop mnemo="LabelLetterTemplates">Briefvorlage:</prop>
        <prop mnemo="LabelMailTemplate">E-Mail</prop>
        <prop mnemo="radioUseSame">gleiche Vorlage wie E-Mail verwenden</prop>
        <prop mnemo="LabelLetterTemplate">Serienbrief</prop>
        <prop mnemo="LabelAttachmentTab">Selektierte Anlagen</prop>
        <prop mnemo="LabelAttachments">Anlagen:</prop>
        <prop mnemo="LabelTest">Test:</prop>
        <prop mnemo="CBTestEmailAddress">Test - E-Mail an folgende Adresse schicken:</prop>
        <prop mnemo="send">Verschicken!</prop>
        <prop mnemo="generate">Generieren!</prop>
        <prop mnemo="addAttachment">Hinzufügen...</prop>
        <prop mnemo="addAttachmentTitle">Bitte wählen Sie eine Datei als Anlage aus</prop>
        <prop mnemo="addTemplateTitle">Bitte wählen Sie eine Datei als Vorlage aus</prop>
        <prop mnemo="addLetterTemplate">Neu...</prop>
        <prop mnemo="addMailTemplate">Neu...</prop>
        <prop mnemo="selectLetterTemplate">Auswählen...</prop>
        <prop mnemo="selectMailTemplate">Auswählen...</prop>
        <prop mnemo="noAttachments">keine</prop>
        <prop mnemo="selectTemplate">Bitte wählen Sie die entsprechenden Vorlagen aus!</prop>
        <prop mnemo="testDocTitleEmail">Test E-Mail</prop>
        <prop mnemo="testDocTextEmail">Bitte überprüfen Sie, ob die gesendete E-Mail ihren Erwartungen entspricht.</prop>
        <prop mnemo="testDocTitleCombined">Test Versand</prop>
        <prop mnemo="testDocTextCombined">Bitte überprüfen Sie, ob die gesendete E-Mail und der generierte Serienbrief ihren Erwartungen entspricht.</prop>
        <prop mnemo="testDocTitleLetter">Test Serienbrief</prop>
        <prop mnemo="testDocTextLetter">Bitte überprüfen Sie, ob der generierte Serienbrief ihren Erwartungen entspricht.</prop>
        <prop mnemo="mergeDocTitle">Generiertes Dokument</prop>
        <prop mnemo="mergeDocText">Nachfolgend finden Sie das generierte Serienbriefdokument:</prop>
        <prop mnemo="mailFinishedTitle">E-Mails verschickt</prop>
        <prop mnemo="mailFinishedText">Die E-Mails wurden erfolgreich generiert und verschickt.</prop>
        <prop mnemo="search">Suchen in Versandgeschichte</prop>
        <prop mnemo="searchresult">Gefundene Versandeinträge</prop>
        <prop mnemo="pageTitleSelectionListMailing">Versandeinträge gemäss Selektion</prop>
        <prop mnemo="detailMailing">Detail des Versandeinträges</prop>
        <prop mnemo="recipients">Empfänger</prop>
        <prop mnemo="selectAll">Alle auswählen</prop>
        <prop mnemo="autoGenDocDescription">Automatisch erzeugter Eintrag.</prop>
    </local>
    <local scope="error">
        <prop mnemo="mergeFieldNotFound">Folgende Vorlagenfelder können nicht zugewiesen werden: </prop>
    </local>
</map>
